// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: extensions/extensions.proto

import { objectType, inputObjectType, enumType, nullable, nonNull } from "nexus";
import * as $$testapis$node$lib$extensions from "@testapis/node/lib/extensions";
export type $$testapis$node$lib$extensions$testapi$extensions$TestPrefixPrefixedMessage = $$testapis$node$lib$extensions.testapi.extensions.IPrefixedMessage;
export type $$testapis$node$lib$extensions$testapi$extensions$TestPrefixPrefixedMessageInnerMessage = $$testapis$node$lib$extensions.testapi.extensions.PrefixedMessage.IInnerMessage;
export const TestPrefixPrefixedMessage = objectType({
    name: "TestPrefixPrefixedMessage",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: "",
            resolve(root) { return root.body!; }
        });
        t.field("prefixedEnum", {
            type: nullable("TestPrefixPrefixedEnum"),
            description: "",
            resolve(root) { return root.prefixedEnum ?? null; }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$extensions$testapi$extensions$TestPrefixPrefixedMessage" }
});
export const TestPrefixPrefixedMessageInnerMessage = objectType({
    name: "TestPrefixPrefixedMessageInnerMessage",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: "",
            resolve(root) { return root.body!; }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$extensions$testapi$extensions$TestPrefixPrefixedMessageInnerMessage" }
});
export const TestPrefixPrefixedMessageInput = inputObjectType({
    name: "TestPrefixPrefixedMessageInput",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: ""
        });
        t.field("prefixedEnum", {
            type: nullable("TestPrefixPrefixedEnum"),
            description: ""
        });
    }
});
export const TestPrefixPrefixedMessageInnerMessageInput = inputObjectType({
    name: "TestPrefixPrefixedMessageInnerMessageInput",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: ""
        });
    }
});
export const TestPrefixPrefixedEnum = enumType({
    name: "TestPrefixPrefixedEnum",
    description: "",
    members: [
        {
            name: "PREFIXED_ENUM_UNSPECIFIED",
            value: 0
        },
        {
            name: "PREFIXED_FOO",
            value: 1
        },
        {
            name: "PREFIXED_BAR",
            value: 2
        }
    ]
});
