// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: extensions/extensions.proto

import { objectType, enumType, nullable, nonNull } from "nexus";
import * as $$testapis$node$lib$extensions$extensions_pb from "@testapis/node/lib/extensions/extensions_pb";
export type $$testapis$node$lib$extensions$extensions_pb$TestPrefixPrefixedMessage = $$testapis$node$lib$extensions$extensions_pb.PrefixedMessage;
export type $$testapis$node$lib$extensions$extensions_pb$TestPrefixPrefixedMessageInnerMessage = $$testapis$node$lib$extensions$extensions_pb.PrefixedMessage.InnerMessage;
export const TestPrefixPrefixedMessage = objectType({
    name: "TestPrefixPrefixedMessage",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: "",
            resolve(root) { return root.getBody(); }
        });
        t.field("prefixedEnum", {
            type: nullable("TestPrefixPrefixedEnum"),
            description: "",
            resolve(root) { return root.getPrefixedEnum(); }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$extensions$extensions_pb$TestPrefixPrefixedMessage" }
});
export const TestPrefixPrefixedMessageInnerMessage = objectType({
    name: "TestPrefixPrefixedMessageInnerMessage",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: "",
            resolve(root) { return root.getBody(); }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$extensions$extensions_pb$TestPrefixPrefixedMessageInnerMessage" }
});
export const TestPrefixPrefixedEnum = enumType({
    name: "TestPrefixPrefixedEnum",
    description: "",
    members: [
        {
            name: "PREFIXED_ENUM_UNSPECIFIED",
            value: 0
        },
        {
            name: "PREFIXED_FOO",
            value: 1
        },
        {
            name: "PREFIXED_BAR",
            value: 2
        }
    ]
});
