// @generated by protoc-gen-pothos v0.7.0 with parameter "import_prefix=@proto-graphql/e2e-testapis-ts-proto/lib/,pothos_builder_path=../builder,scalar=int64=String,scalar=uint64=String,scalar=sint64=String,scalar=fixed64=String,scalar=sfixed64=String,scalar=google.protobuf.Int64Value=String,scalar=google.protobuf.UInt64Value=String,scalar=google.protobuf.SInt64Value=String,scalar=google.protobuf.Fixed64Value=String,scalar=google.protobuf.SFixed64Value=String"
// @generated from file testapis/imports/same_dir/base.proto (package testapis.imports.same_dir, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import {
  SharedEnum,
  SharedMessage,
} from "@proto-graphql/e2e-testapis-ts-proto/lib/testapis/imports/same_dir/base";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const SharedMessage$Ref = builder.objectRef<SharedMessage>(
  "SharedMessage",
);
builder.objectType(SharedMessage$Ref, {
  name: "SharedMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return (source as SharedMessage | { $type: string & {}; }).$type ===
      "testapis.imports.same_dir.SharedMessage";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.imports.same_dir.SharedMessage",
      name: "SharedMessage",
      package: "testapis.imports.same_dir",
    },
  },
});

export type SharedMessageInput$Shape = { body: SharedMessage["body"]; };

export const SharedMessageInput$Ref: InputObjectRef<SharedMessageInput$Shape> =
  builder.inputRef<SharedMessageInput$Shape>("SharedMessageInput").implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.imports.same_dir.SharedMessage",
        name: "SharedMessage",
        package: "testapis.imports.same_dir",
      },
    },
  });

export const SharedEnum$Ref: EnumRef<SharedEnum, SharedEnum> = builder.enumType(
  "SharedEnum",
  {
    values: {
      FOO: {
        value: 1,
        extensions: { protobufEnumValue: { name: "SHARED_ENUM_FOO" } },
      },
    } as const,
    extensions: {
      protobufEnum: {
        name: "SharedEnum",
        fullName: "testapis.imports.same_dir.SharedEnum",
        package: "testapis.imports.same_dir",
      },
    },
  },
);
