// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-ts-proto/lib/,pothos_builder_path=../builder,scalar=int64=String,scalar=uint64=String,scalar=sint64=String,scalar=fixed64=String,scalar=sfixed64=String,scalar=google.protobuf.Int64Value=String,scalar=google.protobuf.UInt64Value=String,scalar=google.protobuf.SInt64Value=String,scalar=google.protobuf.Fixed64Value=String,scalar=google.protobuf.SFixed64Value=String"
// @generated from file testapis/multipkgs/subpkg2/types.proto (package testapis.multipkgs.subpkg1, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { MessageWithSubpkg } from "@proto-graphql/e2e-testapis-ts-proto/lib/testapis/multipkgs/subpkg2/types";
import {
  SubpkgEnum$Ref,
  SubpkgMessage$Ref,
  SubpkgMessageInput$Ref,
  SubpkgMessageInput$Shape,
} from "../subpkg1/types.pb.pothos";
import { SubpkgEnum } from "@proto-graphql/e2e-testapis-ts-proto/lib/testapis/multipkgs/subpkg1/types";
import { InputObjectRef } from "@pothos/core";

export const MessageWithSubpkg$Ref = builder.objectRef<MessageWithSubpkg>(
  "MessageWithSubpkg",
);
builder.objectType(MessageWithSubpkg$Ref, {
  name: "MessageWithSubpkg",
  fields: (t) => ({
    message: t.expose("message", {
      type: SubpkgMessage$Ref,
      nullable: true,
      extensions: {
        protobufField: {
          name: "message",
          typeFullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
        },
      },
    }),
    enum: t.field({
      type: SubpkgEnum$Ref,
      nullable: true,
      resolve: (source) => {
        if (source.enum === SubpkgEnum.SUBPKG_ENUM_UNSPECIFIED) {
          return null;
        }

        return source.enum;
      },
      extensions: {
        protobufField: {
          name: "enum",
          typeFullName: "testapis.multipkgs.subpkg1.SubpkgEnum",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return (source as MessageWithSubpkg | { $type: string & {}; }).$type ===
      "testapis.multipkgs.subpkg1.MessageWithSubpkg";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.multipkgs.subpkg1.MessageWithSubpkg",
      name: "MessageWithSubpkg",
      package: "testapis.multipkgs.subpkg1",
    },
  },
});

export type MessageWithSubpkgInput$Shape = {
  message?: SubpkgMessageInput$Shape | null;
  enum?: MessageWithSubpkg["enum"] | null;
};

export const MessageWithSubpkgInput$Ref: InputObjectRef<
  MessageWithSubpkgInput$Shape
> = builder.inputRef<MessageWithSubpkgInput$Shape>("MessageWithSubpkgInput")
  .implement({
    fields: (t) => ({
      message: t.field({
        type: SubpkgMessageInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "message",
            typeFullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
          },
        },
      }),
      enum: t.field({
        type: SubpkgEnum$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "enum",
            typeFullName: "testapis.multipkgs.subpkg1.SubpkgEnum",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.multipkgs.subpkg1.MessageWithSubpkg",
        name: "MessageWithSubpkg",
        package: "testapis.multipkgs.subpkg1",
      },
    },
  });
