packages:
  - "packages/**"
  - "devPackages/**"
  - "tests/**"

catalog:
  "@bufbuild/protobuf": "2.10.2"
  "@bufbuild/protoplugin": "2.10.2"
  "@bufbuild/protoc-gen-es": "2.10.2"
  case-anything: "^2.1.13"
  change-case: "^4.1.2"
  dprint-node: "^1.0.8"
  ts-poet: "^6.3.0"

catalogs:
  typescript-v5.8:
    typescript: "5.8.3"
  test:
    graphql: "16.9.0"
    graphql-scalars: "1.23.0"
    "@pothos/core": "3.41.1"
    long: "5.2.1"
  protobuf-es-v1:
    "@bufbuild/protobuf": "1.8.0"
    "@bufbuild/protoc-gen-es": "1.8.0"
