packages:
  - "packages/**"
  - "devPackages/**"
  - "e2e/**"

catalog:
  "@bufbuild/protobuf": "2.1.0"
  "@bufbuild/protoplugin": "2.1.0"
  "@bufbuild/protoc-gen-es": "2.1.0"
  "@types/google-protobuf": "3.15.12"
  case-anything: "^2.1.13"
  change-case: "^4.1.2"
  ts-poet: "^6.3.0"

catalogs:
  test:
    graphql: "16.9.0"
    graphql-scalars: "1.23.0"
    "@pothos/core": "3.41.1"
    "google-protobuf": "3.21.4"
    long: "5.2.1"
    nexus: "1.3.0"
    protobufjs: "7.2.5"
  protobuf-es-v1:
    "@bufbuild/protobuf": "1.8.0"
    "@bufbuild/protoc-gen-es": "1.8.0"
