packages:
  - "packages/**"
  - "devPackages/**"
  - "e2e/**"

catalog:
  "@bufbuild/protobuf": "^1.8.0"
  "@bufbuild/protoplugin": "^1.8.0"
  "@bufbuild/protoc-gen-es": "^1.8.0"
  case-anything: "^2.1.13"
  change-case: "^4.1.2"
  ts-poet: "^6.3.0"

catalogs:
  protobuf-es-v1:
    "@bufbuild/protobuf": "^1.8.0"
