// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: nested/nested.proto

import { objectType, enumType } from "nexus";
import * as $$testapis$node$lib$nested$nested_pb from "@testapis/node/lib/nested/nested_pb";
export type $$testapis$node$lib$nested$nested_pb$ParentMessage = $$testapis$node$lib$nested$nested_pb.ParentMessage;
export type $$testapis$node$lib$nested$nested_pb$ParentMessageNestedMessage = $$testapis$node$lib$nested$nested_pb.ParentMessage.NestedMessage;
export const ParentMessage = objectType({
    name: "ParentMessage",
    description: "",
    definition(t) {
        t.nonNull.string("body", {
            description: "",
            resolve(root) { return root.getBody(); }
        });
        t.nullable.field("nested", {
            description: "",
            type: "ParentMessageNestedMessage",
            resolve(root) { return root.getNested() ?? null; }
        });
        t.nullable.field("nestedEnum", {
            description: "",
            type: "ParentMessageNestedEnum",
            resolve(root) { return root.getNestedEnum(); }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$nested$nested_pb$ParentMessage" }
});
export const ParentMessageNestedMessage = objectType({
    name: "ParentMessageNestedMessage",
    description: "",
    definition(t) {
        t.nonNull.string("nestedBody", {
            description: "",
            resolve(root) { return root.getNestedBody(); }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$nested$nested_pb$ParentMessageNestedMessage" }
});
export const ParentMessageNestedEnum = enumType({
    name: "ParentMessageNestedEnum",
    description: "",
    members: [
        {
            name: "NESTED_ENUM_UNSPECIFIED",
            value: 0
        },
        {
            name: "FOO",
            value: 1
        },
        {
            name: "BAR",
            value: 2
        }
    ]
});
