// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es-v2/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es"
// @generated from file testapis/multipkgs/subpkg1/types.proto (package testapis.multipkgs.subpkg1, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { create, isMessage, MessageShape } from "@bufbuild/protobuf";
import {
  SubpkgEnum,
  SubpkgMessage,
  SubpkgMessageSchema,
} from "@proto-graphql/e2e-testapis-protobuf-es-v2/lib/testapis/multipkgs/subpkg1/types_pb";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const SubpkgMessage$Ref = builder.objectRef<
  MessageShape<typeof SubpkgMessageSchema>
>("SubpkgMessage");
builder.objectType(SubpkgMessage$Ref, {
  name: "SubpkgMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, SubpkgMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
      name: "SubpkgMessage",
      package: "testapis.multipkgs.subpkg1",
    },
  },
});

export type SubpkgMessageInput$Shape = { body: SubpkgMessage["body"]; };

export const SubpkgMessageInput$Ref: InputObjectRef<SubpkgMessageInput$Shape> =
  builder.inputRef<SubpkgMessageInput$Shape>("SubpkgMessageInput").implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
        name: "SubpkgMessage",
        package: "testapis.multipkgs.subpkg1",
      },
    },
  }) as InputObjectRef<SubpkgMessageInput$Shape>;

export function SubpkgMessageInput$toProto(
  input: SubpkgMessageInput$Shape | null | undefined,
): SubpkgMessage {
  return create(SubpkgMessageSchema, { body: input?.body ?? undefined });
}

export const SubpkgEnum$Ref: EnumRef<SubpkgEnum, SubpkgEnum> = builder.enumType(
  "SubpkgEnum",
  {
    values: {
      FOO: { value: 1, extensions: { protobufEnumValue: { name: "FOO" } } },
      BAR: { value: 2, extensions: { protobufEnumValue: { name: "BAR" } } },
    } as const,
    extensions: {
      protobufEnum: {
        name: "SubpkgEnum",
        fullName: "testapis.multipkgs.subpkg1.SubpkgEnum",
        package: "testapis.multipkgs.subpkg1",
      },
    },
  },
);
