// @generated by protoc-gen-pothos v0.7.0 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es-v2/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es"
// @generated from file testapis/options/input_no_partial/input_no_partial.proto (package testapis.options.input_no_partial, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { create, isMessage, MessageShape } from "@bufbuild/protobuf";
import {
  NoPartialInputMessage,
  NoPartialInputMessageSchema,
  ParentMessage,
  ParentMessageSchema,
  PartialableInputMessage,
  PartialableInputMessageSchema,
} from "@proto-graphql/e2e-testapis-protobuf-es-v2/lib/testapis/options/input_no_partial/input_no_partial_pb";
import { InputObjectRef } from "@pothos/core";

export const ParentMessage$Ref = builder.objectRef<
  MessageShape<typeof ParentMessageSchema>
>("ParentMessage");
builder.objectType(ParentMessage$Ref, {
  name: "ParentMessage",
  fields: (t) => ({
    partialableInputMessage: t.field({
      type: PartialableInputMessage$Ref,
      nullable: false,
      description: "Required.",
      resolve: (source) => {
        return source.partialableInputMessage!;
      },
      extensions: {
        protobufField: {
          name: "partialable_input_message",
          typeFullName:
            "testapis.options.input_no_partial.PartialableInputMessage",
        },
      },
    }),
    noPartialInputMessage: t.field({
      type: NoPartialInputMessage$Ref,
      nullable: false,
      description: "Required.",
      resolve: (source) => {
        return source.noPartialInputMessage!;
      },
      extensions: {
        protobufField: {
          name: "no_partial_input_message",
          typeFullName:
            "testapis.options.input_no_partial.NoPartialInputMessage",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, ParentMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.options.input_no_partial.ParentMessage",
      name: "ParentMessage",
      package: "testapis.options.input_no_partial",
    },
  },
});

export const PartialableInputMessage$Ref = builder.objectRef<
  MessageShape<typeof PartialableInputMessageSchema>
>("PartialableInputMessage");
builder.objectType(PartialableInputMessage$Ref, {
  name: "PartialableInputMessage",
  fields: (t) => ({
    id: t.expose("id", {
      type: "Int64",
      nullable: false,
      description: "Required.",
      extensions: { protobufField: { name: "id", typeFullName: "uint64" } },
    }),
    body: t.expose("body", {
      type: "String",
      nullable: false,
      description: "Required.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, PartialableInputMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.options.input_no_partial.PartialableInputMessage",
      name: "PartialableInputMessage",
      package: "testapis.options.input_no_partial",
    },
  },
});

export const NoPartialInputMessage$Ref = builder.objectRef<
  MessageShape<typeof NoPartialInputMessageSchema>
>("NoPartialInputMessage");
builder.objectType(NoPartialInputMessage$Ref, {
  name: "NoPartialInputMessage",
  fields: (t) => ({
    id: t.expose("id", {
      type: "Int64",
      nullable: false,
      description: "Required.",
      extensions: { protobufField: { name: "id", typeFullName: "uint64" } },
    }),
    body: t.expose("body", {
      type: "String",
      nullable: false,
      description: "Required.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, NoPartialInputMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.options.input_no_partial.NoPartialInputMessage",
      name: "NoPartialInputMessage",
      package: "testapis.options.input_no_partial",
      options: { "[graphql.input_type]": { noPartial: true } },
    },
  },
});

export type ParentMessageInput$Shape = {
  partialableInputMessage: PartialableInputMessageInput$Shape;
  noPartialInputMessage: NoPartialInputMessageInput$Shape;
};

export const ParentMessageInput$Ref: InputObjectRef<ParentMessageInput$Shape> =
  builder.inputRef<ParentMessageInput$Shape>("ParentMessageInput").implement({
    fields: (t) => ({
      partialableInputMessage: t.field({
        type: PartialableInputMessageInput$Ref,
        required: true,
        description: "Required.",
        extensions: {
          protobufField: {
            name: "partialable_input_message",
            typeFullName:
              "testapis.options.input_no_partial.PartialableInputMessage",
          },
        },
      }),
      noPartialInputMessage: t.field({
        type: NoPartialInputMessageInput$Ref,
        required: true,
        description: "Required.",
        extensions: {
          protobufField: {
            name: "no_partial_input_message",
            typeFullName:
              "testapis.options.input_no_partial.NoPartialInputMessage",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.options.input_no_partial.ParentMessage",
        name: "ParentMessage",
        package: "testapis.options.input_no_partial",
      },
    },
  }) as InputObjectRef<ParentMessageInput$Shape>;

export function ParentMessageInput$toProto(
  input: ParentMessageInput$Shape | null | undefined,
): ParentMessage {
  return create(ParentMessageSchema, {
    partialableInputMessage: input?.partialableInputMessage
      ? PartialableInputMessageInput$toProto(input.partialableInputMessage)
      : undefined,
    noPartialInputMessage: input?.noPartialInputMessage
      ? NoPartialInputMessageInput$toProto(input.noPartialInputMessage)
      : undefined,
  });
}

export type PartialableInputMessageInput$Shape = {
  id: PartialableInputMessage["id"];
  body: PartialableInputMessage["body"];
};

export const PartialableInputMessageInput$Ref: InputObjectRef<
  PartialableInputMessageInput$Shape
> = builder.inputRef<PartialableInputMessageInput$Shape>(
  "PartialableInputMessageInput",
).implement({
  fields: (t) => ({
    id: t.field({
      type: "Int64",
      required: true,
      description: "Required.",
      extensions: { protobufField: { name: "id", typeFullName: "uint64" } },
    }),
    body: t.field({
      type: "String",
      required: true,
      description: "Required.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.options.input_no_partial.PartialableInputMessage",
      name: "PartialableInputMessage",
      package: "testapis.options.input_no_partial",
    },
  },
}) as InputObjectRef<PartialableInputMessageInput$Shape>;

export function PartialableInputMessageInput$toProto(
  input: PartialableInputMessageInput$Shape | null | undefined,
): PartialableInputMessage {
  return create(PartialableInputMessageSchema, {
    id: input?.id ?? undefined,
    body: input?.body ?? undefined,
  });
}

export type NoPartialInputMessageInput$Shape = {
  id: NoPartialInputMessage["id"];
  body: NoPartialInputMessage["body"];
};

export const NoPartialInputMessageInput$Ref: InputObjectRef<
  NoPartialInputMessageInput$Shape
> = builder.inputRef<NoPartialInputMessageInput$Shape>(
  "NoPartialInputMessageInput",
).implement({
  fields: (t) => ({
    id: t.field({
      type: "Int64",
      required: true,
      description: "Required.",
      extensions: { protobufField: { name: "id", typeFullName: "uint64" } },
    }),
    body: t.field({
      type: "String",
      required: true,
      description: "Required.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.options.input_no_partial.NoPartialInputMessage",
      name: "NoPartialInputMessage",
      package: "testapis.options.input_no_partial",
      options: { "[graphql.input_type]": { noPartial: true } },
    },
  },
}) as InputObjectRef<NoPartialInputMessageInput$Shape>;

export function NoPartialInputMessageInput$toProto(
  input: NoPartialInputMessageInput$Shape | null | undefined,
): NoPartialInputMessage {
  return create(NoPartialInputMessageSchema, {
    id: input?.id ?? undefined,
    body: input?.body ?? undefined,
  });
}
