// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: testapis/oneof/oneof.proto

import { objectType, inputObjectType, unionType, nullable, nonNull } from "nexus";
import * as $$testapis$node$lib$testapis$oneof from "@testapis/node/lib/testapis/oneof";
export type $$testapis$node$lib$testapis$oneof$testapis$oneof$OneofParent = $$testapis$node$lib$testapis$oneof.testapis.oneof.IOneofParent;
export type $$testapis$node$lib$testapis$oneof$testapis$oneof$OneofMemberMessage1 = $$testapis$node$lib$testapis$oneof.testapis.oneof.IOneofMemberMessage1;
export type $$testapis$node$lib$testapis$oneof$testapis$oneof$OneofMemberMessage2 = $$testapis$node$lib$testapis$oneof.testapis.oneof.IOneofMemberMessage2;
export type $$testapis$node$lib$testapis$oneof$testapis$oneof$OneofParent_required_oneof_members = ($$testapis$node$lib$testapis$oneof.testapis.oneof.IOneofMemberMessage1 & {
    __protobufTypeName: "testapis.oneof.OneofMemberMessage1";
}) | ($$testapis$node$lib$testapis$oneof.testapis.oneof.IOneofMemberMessage2 & {
    __protobufTypeName: "testapis.oneof.OneofMemberMessage2";
});
export type $$testapis$node$lib$testapis$oneof$testapis$oneof$OneofParent_optional_oneof_members = ($$testapis$node$lib$testapis$oneof.testapis.oneof.IOneofMemberMessage1 & {
    __protobufTypeName: "testapis.oneof.OneofMemberMessage1";
}) | ($$testapis$node$lib$testapis$oneof.testapis.oneof.IOneofMemberMessage2 & {
    __protobufTypeName: "testapis.oneof.OneofMemberMessage2";
});
export const OneofParentRequiredOneofMembers = unionType({
    name: "OneofParentRequiredOneofMembers",
    description: "Required. disallow not_set.",
    definition(t) {
        t.members("OneofMemberMessage1", "OneofMemberMessage2");
    },
    resolveType(item) {
        if (item.__protobufTypeName === "testapis.oneof.OneofMemberMessage1") {
            return "OneofMemberMessage1";
        }
        if (item.__protobufTypeName === "testapis.oneof.OneofMemberMessage2") {
            return "OneofMemberMessage2";
        }
        throw "unreachable";
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$testapis$oneof$testapis$oneof$OneofParent_required_oneof_members" }
});
export const OneofParentOptionalOneofMembers = unionType({
    name: "OneofParentOptionalOneofMembers",
    description: "",
    definition(t) {
        t.members("OneofMemberMessage1", "OneofMemberMessage2");
    },
    resolveType(item) {
        if (item.__protobufTypeName === "testapis.oneof.OneofMemberMessage1") {
            return "OneofMemberMessage1";
        }
        if (item.__protobufTypeName === "testapis.oneof.OneofMemberMessage2") {
            return "OneofMemberMessage2";
        }
        throw "unreachable";
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$testapis$oneof$testapis$oneof$OneofParent_optional_oneof_members" }
});
export const OneofParent = objectType({
    name: "OneofParent",
    description: "",
    definition(t) {
        t.field("normalField", {
            type: nonNull("String"),
            description: "",
            resolve(root) { return root.normalField!; }
        });
        t.field("required_oneof_members", {
            type: nonNull("OneofParentRequiredOneofMembers"),
            description: "Required. disallow not_set.",
            resolve(root) {
                if (root.requiredMessage1) {
                    return Object.assign(root.requiredMessage1, { __protobufTypeName: ("testapis.oneof.OneofMemberMessage1" as const) });
                }
                if (root.requiredMessage2) {
                    return Object.assign(root.requiredMessage2, { __protobufTypeName: ("testapis.oneof.OneofMemberMessage2" as const) });
                }
                throw "unreachable";
            }
        });
        t.field("optional_oneof_members", {
            type: nullable("OneofParentOptionalOneofMembers"),
            description: "",
            resolve(root) {
                if (root.optoinalMessage1) {
                    return Object.assign(root.optoinalMessage1, { __protobufTypeName: ("testapis.oneof.OneofMemberMessage1" as const) });
                }
                if (root.optoinalMessage2) {
                    return Object.assign(root.optoinalMessage2, { __protobufTypeName: ("testapis.oneof.OneofMemberMessage2" as const) });
                }
                return null;
            }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$testapis$oneof$testapis$oneof$OneofParent" }
});
export const OneofMemberMessage1 = objectType({
    name: "OneofMemberMessage1",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: "",
            resolve(root) { return root.body!; }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$testapis$oneof$testapis$oneof$OneofMemberMessage1" }
});
export const OneofMemberMessage2 = objectType({
    name: "OneofMemberMessage2",
    description: "",
    definition(t) {
        t.field("imageUrl", {
            type: nonNull("String"),
            description: "",
            resolve(root) { return root.imageUrl!; }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node$lib$testapis$oneof$testapis$oneof$OneofMemberMessage2" }
});
export const OneofParentInput = inputObjectType({
    name: "OneofParentInput",
    description: "",
    definition(t) {
        t.field("normalField", {
            type: nonNull("String"),
            description: ""
        });
        t.field("requiredMessage1", {
            type: nullable("OneofMemberMessage1Input"),
            description: ""
        });
        t.field("requiredMessage2", {
            type: nullable("OneofMemberMessage2Input"),
            description: ""
        });
        t.field("optoinalMessage1", {
            type: nullable("OneofMemberMessage1Input"),
            description: ""
        });
        t.field("optoinalMessage2", {
            type: nullable("OneofMemberMessage2Input"),
            description: ""
        });
    }
});
export const OneofMemberMessage1Input = inputObjectType({
    name: "OneofMemberMessage1Input",
    description: "",
    definition(t) {
        t.field("body", {
            type: nonNull("String"),
            description: ""
        });
    }
});
export const OneofMemberMessage2Input = inputObjectType({
    name: "OneofMemberMessage2Input",
    description: "",
    definition(t) {
        t.field("imageUrl", {
            type: nonNull("String"),
            description: ""
        });
    }
});
