// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es-v2/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es"
// @generated from file testapis/behavior/field_comments/field_comments.proto (package testapis.behavior.field_comments, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { create, isMessage, MessageShape } from "@bufbuild/protobuf";
import {
  FieldBehaviorCommentsMessage,
  FieldBehaviorCommentsMessage_Post,
  FieldBehaviorCommentsMessage_PostSchema,
  FieldBehaviorCommentsMessageSchema,
} from "@proto-graphql/e2e-testapis-protobuf-es-v2/lib/testapis/behavior/field_comments/field_comments_pb";
import { InputObjectRef } from "@pothos/core";

export const FieldBehaviorCommentsMessage$Ref = builder.objectRef<
  MessageShape<typeof FieldBehaviorCommentsMessageSchema>
>("FieldBehaviorCommentsMessage");
builder.objectType(FieldBehaviorCommentsMessage$Ref, {
  name: "FieldBehaviorCommentsMessage",
  fields: (t) => ({
    requiredField: t.field({
      type: FieldBehaviorCommentsMessagePost$Ref,
      nullable: false,
      description: "Required.",
      resolve: (source) => {
        return source.requiredField!;
      },
      extensions: {
        protobufField: {
          name: "required_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
    requiredOutputOnlyField: t.field({
      type: FieldBehaviorCommentsMessagePost$Ref,
      nullable: false,
      description: "Required. Output only.",
      resolve: (source) => {
        return source.requiredOutputOnlyField!;
      },
      extensions: {
        protobufField: {
          name: "required_output_only_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
    outputOnlyRequiredField: t.field({
      type: FieldBehaviorCommentsMessagePost$Ref,
      nullable: false,
      description: "Output only. Required.",
      resolve: (source) => {
        return source.outputOnlyRequiredField!;
      },
      extensions: {
        protobufField: {
          name: "output_only_required_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
    outputOnlyField: t.expose("outputOnlyField", {
      type: FieldBehaviorCommentsMessagePost$Ref,
      nullable: true,
      description: "Output only.",
      extensions: {
        protobufField: {
          name: "output_only_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, FieldBehaviorCommentsMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.behavior.field_comments.FieldBehaviorCommentsMessage",
      name: "FieldBehaviorCommentsMessage",
      package: "testapis.behavior.field_comments",
    },
  },
});

export const FieldBehaviorCommentsMessagePost$Ref = builder.objectRef<
  MessageShape<typeof FieldBehaviorCommentsMessage_PostSchema>
>("FieldBehaviorCommentsMessagePost");
builder.objectType(FieldBehaviorCommentsMessagePost$Ref, {
  name: "FieldBehaviorCommentsMessagePost",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, FieldBehaviorCommentsMessage_PostSchema);
  },
  extensions: {
    protobufMessage: {
      fullName:
        "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
      name: "Post",
      package: "testapis.behavior.field_comments",
    },
  },
});

export type FieldBehaviorCommentsMessageInput$Shape = {
  requiredField: FieldBehaviorCommentsMessagePostInput$Shape;
  requiredInputOnlyField: FieldBehaviorCommentsMessagePostInput$Shape;
  inputOnlyRequiredField: FieldBehaviorCommentsMessagePostInput$Shape;
  inputOnlyField?: FieldBehaviorCommentsMessagePostInput$Shape | null;
};

export const FieldBehaviorCommentsMessageInput$Ref: InputObjectRef<
  FieldBehaviorCommentsMessageInput$Shape
> = builder.inputRef<FieldBehaviorCommentsMessageInput$Shape>(
  "FieldBehaviorCommentsMessageInput",
).implement({
  fields: (t) => ({
    requiredField: t.field({
      type: FieldBehaviorCommentsMessagePostInput$Ref,
      required: true,
      description: "Required.",
      extensions: {
        protobufField: {
          name: "required_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
    requiredInputOnlyField: t.field({
      type: FieldBehaviorCommentsMessagePostInput$Ref,
      required: true,
      description: "Required. Input only.",
      extensions: {
        protobufField: {
          name: "required_input_only_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
    inputOnlyRequiredField: t.field({
      type: FieldBehaviorCommentsMessagePostInput$Ref,
      required: true,
      description: "Input only. Required.",
      extensions: {
        protobufField: {
          name: "input_only_required_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
    inputOnlyField: t.field({
      type: FieldBehaviorCommentsMessagePostInput$Ref,
      required: false,
      description: "Input only.",
      extensions: {
        protobufField: {
          name: "input_only_field",
          typeFullName:
            "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
        },
      },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.behavior.field_comments.FieldBehaviorCommentsMessage",
      name: "FieldBehaviorCommentsMessage",
      package: "testapis.behavior.field_comments",
    },
  },
}) as InputObjectRef<FieldBehaviorCommentsMessageInput$Shape>;

export function FieldBehaviorCommentsMessageInput$toProto(
  input: FieldBehaviorCommentsMessageInput$Shape | null | undefined,
): FieldBehaviorCommentsMessage {
  return create(FieldBehaviorCommentsMessageSchema, {
    requiredField: input?.requiredField
      ? FieldBehaviorCommentsMessagePostInput$toProto(input.requiredField)
      : undefined,
    requiredInputOnlyField: input?.requiredInputOnlyField
      ? FieldBehaviorCommentsMessagePostInput$toProto(
        input.requiredInputOnlyField,
      )
      : undefined,
    inputOnlyRequiredField: input?.inputOnlyRequiredField
      ? FieldBehaviorCommentsMessagePostInput$toProto(
        input.inputOnlyRequiredField,
      )
      : undefined,
    inputOnlyField: input?.inputOnlyField
      ? FieldBehaviorCommentsMessagePostInput$toProto(input.inputOnlyField)
      : undefined,
  });
}

export type FieldBehaviorCommentsMessagePostInput$Shape = {
  body: FieldBehaviorCommentsMessage_Post["body"];
};

export const FieldBehaviorCommentsMessagePostInput$Ref: InputObjectRef<
  FieldBehaviorCommentsMessagePostInput$Shape
> = builder.inputRef<FieldBehaviorCommentsMessagePostInput$Shape>(
  "FieldBehaviorCommentsMessagePostInput",
).implement({
  fields: (t) => ({
    body: t.field({
      type: "String",
      required: true,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName:
        "testapis.behavior.field_comments.FieldBehaviorCommentsMessage.Post",
      name: "Post",
      package: "testapis.behavior.field_comments",
    },
  },
}) as InputObjectRef<FieldBehaviorCommentsMessagePostInput$Shape>;

export function FieldBehaviorCommentsMessagePostInput$toProto(
  input: FieldBehaviorCommentsMessagePostInput$Shape | null | undefined,
): FieldBehaviorCommentsMessage_Post {
  return create(FieldBehaviorCommentsMessage_PostSchema, {
    body: input?.body ?? undefined,
  });
}
