// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-ts-proto/lib/,pothos_builder_path=../builder,scalar=int64=String,scalar=uint64=String,scalar=sint64=String,scalar=fixed64=String,scalar=sfixed64=String,scalar=google.protobuf.Int64Value=String,scalar=google.protobuf.UInt64Value=String,scalar=google.protobuf.SInt64Value=String,scalar=google.protobuf.Fixed64Value=String,scalar=google.protobuf.SFixed64Value=String"
// @generated from file testapis/edgecases/import_squashed_union/pkg2/types.proto (package testapis.edgecases.import_squashed_union.pkg2, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../../builder";
import { Message } from "@proto-graphql/e2e-testapis-ts-proto/lib/testapis/edgecases/import_squashed_union/pkg2/types";
import {
  SquashedOneof$Ref,
  SquashedOneofInput$Ref,
  SquashedOneofInput$Shape,
} from "../pkg1/types.pb.pothos";
import { InputObjectRef } from "@pothos/core";

export const Message$Ref = builder.objectRef<Message>("Message");
builder.objectType(Message$Ref, {
  name: "Message",
  fields: (t) => ({
    msg: t.field({
      type: SquashedOneof$Ref,
      nullable: true,
      resolve: (source) => {
        const value = source.msg?.msg1;
        if (value == null) {
          return null;
        }
        return value;
      },
      extensions: {
        protobufField: {
          name: "msg",
          typeFullName:
            "testapis.edgecases.import_squashed_union.pkg1.SquashedOneof",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return (source as Message | { $type: string & {}; }).$type ===
      "testapis.edgecases.import_squashed_union.pkg2.Message";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.edgecases.import_squashed_union.pkg2.Message",
      name: "Message",
      package: "testapis.edgecases.import_squashed_union.pkg2",
    },
  },
});

export type MessageInput$Shape = { msg?: SquashedOneofInput$Shape | null; };

export const MessageInput$Ref: InputObjectRef<MessageInput$Shape> = builder
  .inputRef<MessageInput$Shape>("MessageInput").implement({
    fields: (t) => ({
      msg: t.field({
        type: SquashedOneofInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "msg",
            typeFullName:
              "testapis.edgecases.import_squashed_union.pkg1.SquashedOneof",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.edgecases.import_squashed_union.pkg2.Message",
        name: "Message",
        package: "testapis.edgecases.import_squashed_union.pkg2",
      },
    },
  });
