// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es-v2/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es"
// @generated from file testapis/deprecation/file_deprecation.proto (package testapis.deprecation, syntax proto3)
/* eslint-disable */

import { builder } from "../../../builder";
import { create, isMessage, MessageShape } from "@bufbuild/protobuf";
import {
  DeprecatedFileEnum,
  DeprecatedFileMessage,
  DeprecatedFileMessage_InnerMessage,
  DeprecatedFileMessage_InnerMessageSchema,
  DeprecatedFileMessageSchema,
} from "@proto-graphql/e2e-testapis-protobuf-es-v2/lib/testapis/deprecation/file_deprecation_pb";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const DeprecatedFileMessage$Ref = builder.objectRef<
  MessageShape<typeof DeprecatedFileMessageSchema>
>("DeprecatedFileMessage");
builder.objectType(DeprecatedFileMessage$Ref, {
  name: "DeprecatedFileMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
    enum: t.field({
      type: DeprecatedFileEnum$Ref,
      nullable: true,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      resolve: (source) => {
        if (
          source.enum === DeprecatedFileEnum.DEPRECATED_FILE_ENUM_UNSPECIFIED
        ) {
          return null;
        }

        return source.enum;
      },
      extensions: {
        protobufField: {
          name: "enum",
          typeFullName: "testapis.deprecation.DeprecatedFileEnum",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, DeprecatedFileMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage",
      name: "DeprecatedFileMessage",
      package: "testapis.deprecation",
    },
  },
});

export const DeprecatedFileMessageInnerMessage$Ref = builder.objectRef<
  MessageShape<typeof DeprecatedFileMessage_InnerMessageSchema>
>("DeprecatedFileMessageInnerMessage");
builder.objectType(DeprecatedFileMessageInnerMessage$Ref, {
  name: "DeprecatedFileMessageInnerMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, DeprecatedFileMessage_InnerMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage.InnerMessage",
      name: "InnerMessage",
      package: "testapis.deprecation",
    },
  },
});

export type DeprecatedFileMessageInput$Shape = {
  body?: DeprecatedFileMessage["body"] | null;
  enum?: DeprecatedFileMessage["enum"] | null;
};

export const DeprecatedFileMessageInput$Ref: InputObjectRef<
  DeprecatedFileMessageInput$Shape
> = builder.inputRef<DeprecatedFileMessageInput$Shape>(
  "DeprecatedFileMessageInput",
).implement({
  fields: (t) => ({
    body: t.field({
      type: "String",
      required: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
    enum: t.field({
      type: DeprecatedFileEnum$Ref,
      required: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: {
        protobufField: {
          name: "enum",
          typeFullName: "testapis.deprecation.DeprecatedFileEnum",
        },
      },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage",
      name: "DeprecatedFileMessage",
      package: "testapis.deprecation",
    },
  },
}) as InputObjectRef<DeprecatedFileMessageInput$Shape>;

export function DeprecatedFileMessageInput$toProto(
  input: DeprecatedFileMessageInput$Shape | null | undefined,
): DeprecatedFileMessage {
  return create(DeprecatedFileMessageSchema, {
    body: input?.body ?? undefined,
    enum: input?.enum ?? undefined,
  });
}

export type DeprecatedFileMessageInnerMessageInput$Shape = {
  body?: DeprecatedFileMessage_InnerMessage["body"] | null;
};

export const DeprecatedFileMessageInnerMessageInput$Ref: InputObjectRef<
  DeprecatedFileMessageInnerMessageInput$Shape
> = builder.inputRef<DeprecatedFileMessageInnerMessageInput$Shape>(
  "DeprecatedFileMessageInnerMessageInput",
).implement({
  fields: (t) => ({
    body: t.field({
      type: "String",
      required: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage.InnerMessage",
      name: "InnerMessage",
      package: "testapis.deprecation",
    },
  },
}) as InputObjectRef<DeprecatedFileMessageInnerMessageInput$Shape>;

export function DeprecatedFileMessageInnerMessageInput$toProto(
  input: DeprecatedFileMessageInnerMessageInput$Shape | null | undefined,
): DeprecatedFileMessage_InnerMessage {
  return create(DeprecatedFileMessage_InnerMessageSchema, {
    body: input?.body ?? undefined,
  });
}

export const DeprecatedFileEnum$Ref: EnumRef<
  DeprecatedFileEnum,
  DeprecatedFileEnum
> = builder.enumType("DeprecatedFileEnum", {
  values: {
    DEPRECATED_FILE_FOO: {
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      value: 1,
      extensions: { protobufEnumValue: { name: "DEPRECATED_FILE_FOO" } },
    },
    DEPRECATED_FILE_BAR: {
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      value: 2,
      extensions: { protobufEnumValue: { name: "DEPRECATED_FILE_BAR" } },
    },
  } as const,
  extensions: {
    protobufEnum: {
      name: "DeprecatedFileEnum",
      fullName: "testapis.deprecation.DeprecatedFileEnum",
      package: "testapis.deprecation",
    },
  },
});
