// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es-v1"
// @generated from file testapis/basic/empty/empty.proto (package testapis.basic.empty, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { EmptyMessage } from "@proto-graphql/e2e-testapis-protobuf-es/lib/testapis/basic/empty/empty_pb";
import { InputObjectRef } from "@pothos/core";

export const EmptyMessage$Ref = builder.objectRef<EmptyMessage>("EmptyMessage");
builder.objectType(EmptyMessage$Ref, {
  name: "EmptyMessage",
  fields: (t) => ({
    _: t.field({
      type: "Boolean",
      nullable: true,
      description: "noop field",
      resolve: () => true,
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof EmptyMessage;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.basic.empty.EmptyMessage",
      name: "EmptyMessage",
      package: "testapis.basic.empty",
    },
  },
});

export type EmptyMessageInput$Shape = {};

export const EmptyMessageInput$Ref: InputObjectRef<EmptyMessageInput$Shape> =
  builder.inputRef<EmptyMessageInput$Shape>("EmptyMessageInput").implement({
    fields: (t) => ({
      _: t.field({
        type: "Boolean",
        required: false,
        description: "noop field",
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.basic.empty.EmptyMessage",
        name: "EmptyMessage",
        package: "testapis.basic.empty",
      },
    },
  });

export function EmptyMessageInput$toProto(
  input: EmptyMessageInput$Shape | null | undefined,
): EmptyMessage {
  return new EmptyMessage({});
}
