// @generated by protoc-gen-pothos v0.7.0 with parameter "import_prefix=@proto-graphql/e2e-testapis-ts-proto-with-forcelong-number/lib/,pothos_builder_path=../builder,scalar=int64=Int,scalar=uint64=Int,scalar=sint64=Int,scalar=fixed64=Int,scalar=sfixed64=Int,scalar=google.protobuf.Int64Value=Int,scalar=google.protobuf.UInt64Value=Int,scalar=google.protobuf.SInt64Value=Int,scalar=google.protobuf.Fixed64Value=Int,scalar=google.protobuf.SFixed64Value=Int"
// @generated from file testapis/basic/scalars/scalars.proto (package testapis.basic.scalars, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import {
  Message,
  Primitives,
} from "@proto-graphql/e2e-testapis-ts-proto-with-forcelong-number/lib/testapis/basic/scalars/scalars";
import { InputObjectRef } from "@pothos/core";

export const Message$Ref = builder.objectRef<Message>("Message");
builder.objectType(Message$Ref, {
  name: "Message",
  fields: (t) => ({
    requiredPrimitives: t.field({
      type: Primitives$Ref,
      nullable: false,
      description: "Required.",
      resolve: (source) => {
        return source.requiredPrimitives!;
      },
      extensions: {
        protobufField: {
          name: "required_primitives",
          typeFullName: "testapis.basic.scalars.Primitives",
        },
      },
    }),
    optionalPrimitives: t.expose("optionalPrimitives", {
      type: Primitives$Ref,
      nullable: true,
      description: "Optional.",
      extensions: {
        protobufField: {
          name: "optional_primitives",
          typeFullName: "testapis.basic.scalars.Primitives",
        },
      },
    }),
    requiredPrimitivesList: t.field({
      type: [Primitives$Ref],
      nullable: { list: false, items: false },
      description: "Required.",
      resolve: (source) => {
        return source.requiredPrimitivesList!;
      },
      extensions: {
        protobufField: {
          name: "required_primitives_list",
          typeFullName: "testapis.basic.scalars.Primitives",
        },
      },
    }),
    optionalPrimitivesList: t.expose("optionalPrimitivesList", {
      type: [Primitives$Ref],
      nullable: { list: true, items: false },
      description: "Optional.",
      extensions: {
        protobufField: {
          name: "optional_primitives_list",
          typeFullName: "testapis.basic.scalars.Primitives",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return (source as Message | { $type: string & {}; }).$type ===
      "testapis.basic.scalars.Message";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.basic.scalars.Message",
      name: "Message",
      package: "testapis.basic.scalars",
    },
  },
});

export const Primitives$Ref = builder.objectRef<Primitives>("Primitives");
builder.objectType(Primitives$Ref, {
  name: "Primitives",
  fields: (t) => ({
    requiredDoubleValue: t.expose("requiredDoubleValue", {
      type: "Float",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_double_value",
          typeFullName: "double",
        },
      },
    }),
    requiredFloatValue: t.expose("requiredFloatValue", {
      type: "Float",
      nullable: false,
      extensions: {
        protobufField: { name: "required_float_value", typeFullName: "float" },
      },
    }),
    requiredInt32Value: t.expose("requiredInt32Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: { name: "required_int32_value", typeFullName: "int32" },
      },
    }),
    requiredInt64Value: t.expose("requiredInt64Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: { name: "required_int64_value", typeFullName: "int64" },
      },
    }),
    requiredUint32Value: t.expose("requiredUint32Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_uint32_value",
          typeFullName: "uint32",
        },
      },
    }),
    requiredUint64Value: t.expose("requiredUint64Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_uint64_value",
          typeFullName: "uint64",
        },
      },
    }),
    requiredSint32Value: t.expose("requiredSint32Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_sint32_value",
          typeFullName: "sint32",
        },
      },
    }),
    requiredSint64Value: t.expose("requiredSint64Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_sint64_value",
          typeFullName: "sint64",
        },
      },
    }),
    requiredFixed32Value: t.expose("requiredFixed32Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_fixed32_value",
          typeFullName: "fixed32",
        },
      },
    }),
    requiredFixed64Value: t.expose("requiredFixed64Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_fixed64_value",
          typeFullName: "fixed64",
        },
      },
    }),
    requiredSfixed32Value: t.expose("requiredSfixed32Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_sfixed32_value",
          typeFullName: "sfixed32",
        },
      },
    }),
    requiredSfixed64Value: t.expose("requiredSfixed64Value", {
      type: "Int",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_sfixed64_value",
          typeFullName: "sfixed64",
        },
      },
    }),
    requiredBoolValue: t.expose("requiredBoolValue", {
      type: "Boolean",
      nullable: false,
      extensions: {
        protobufField: { name: "required_bool_value", typeFullName: "bool" },
      },
    }),
    requiredStringValue: t.expose("requiredStringValue", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: {
          name: "required_string_value",
          typeFullName: "string",
        },
      },
    }),
    requiredBytesValue: t.field({
      type: "Byte",
      nullable: false,
      resolve: (source) => {
        return Buffer.from(source.requiredBytesValue);
      },
      extensions: {
        protobufField: { name: "required_bytes_value", typeFullName: "bytes" },
      },
    }),
    requiredDoubleValues: t.expose("requiredDoubleValues", {
      type: ["Float"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_double_values",
          typeFullName: "double",
        },
      },
    }),
    requiredFloatValues: t.expose("requiredFloatValues", {
      type: ["Float"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: { name: "required_float_values", typeFullName: "float" },
      },
    }),
    requiredInt32Values: t.expose("requiredInt32Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: { name: "required_int32_values", typeFullName: "int32" },
      },
    }),
    requiredInt64Values: t.expose("requiredInt64Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: { name: "required_int64_values", typeFullName: "int64" },
      },
    }),
    requiredUint32Values: t.expose("requiredUint32Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_uint32_values",
          typeFullName: "uint32",
        },
      },
    }),
    requiredUint64Values: t.expose("requiredUint64Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_uint64_values",
          typeFullName: "uint64",
        },
      },
    }),
    requiredSint32Values: t.expose("requiredSint32Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_sint32_values",
          typeFullName: "sint32",
        },
      },
    }),
    requiredSint64Values: t.expose("requiredSint64Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_sint64_values",
          typeFullName: "sint64",
        },
      },
    }),
    requiredFixed32Values: t.expose("requiredFixed32Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_fixed32_values",
          typeFullName: "fixed32",
        },
      },
    }),
    requiredFixed64Values: t.expose("requiredFixed64Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_fixed64_values",
          typeFullName: "fixed64",
        },
      },
    }),
    requiredSfixed32Values: t.expose("requiredSfixed32Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_sfixed32_values",
          typeFullName: "sfixed32",
        },
      },
    }),
    requiredSfixed64Values: t.expose("requiredSfixed64Values", {
      type: ["Int"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_sfixed64_values",
          typeFullName: "sfixed64",
        },
      },
    }),
    requiredBoolValues: t.expose("requiredBoolValues", {
      type: ["Boolean"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: { name: "required_bool_values", typeFullName: "bool" },
      },
    }),
    requiredStringValues: t.expose("requiredStringValues", {
      type: ["String"],
      nullable: { list: false, items: false },
      extensions: {
        protobufField: {
          name: "required_string_values",
          typeFullName: "string",
        },
      },
    }),
    requiredBytesValues: t.field({
      type: ["Byte"],
      nullable: { list: false, items: false },
      resolve: (source) => {
        return source.requiredBytesValues.map((v) => Buffer.from(v));
      },
      extensions: {
        protobufField: { name: "required_bytes_values", typeFullName: "bytes" },
      },
    }),
  }),
  isTypeOf: (source) => {
    return (source as Primitives | { $type: string & {}; }).$type ===
      "testapis.basic.scalars.Primitives";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.basic.scalars.Primitives",
      name: "Primitives",
      package: "testapis.basic.scalars",
    },
  },
});

export type MessageInput$Shape = {
  requiredPrimitives: PrimitivesInput$Shape;
  optionalPrimitives?: PrimitivesInput$Shape | null;
  requiredPrimitivesList: Array<PrimitivesInput$Shape>;
  optionalPrimitivesList?: Array<PrimitivesInput$Shape> | null;
};

export const MessageInput$Ref: InputObjectRef<MessageInput$Shape> = builder
  .inputRef<MessageInput$Shape>("MessageInput").implement({
    fields: (t) => ({
      requiredPrimitives: t.field({
        type: PrimitivesInput$Ref,
        required: true,
        description: "Required.",
        extensions: {
          protobufField: {
            name: "required_primitives",
            typeFullName: "testapis.basic.scalars.Primitives",
          },
        },
      }),
      optionalPrimitives: t.field({
        type: PrimitivesInput$Ref,
        required: false,
        description: "Optional.",
        extensions: {
          protobufField: {
            name: "optional_primitives",
            typeFullName: "testapis.basic.scalars.Primitives",
          },
        },
      }),
      requiredPrimitivesList: t.field({
        type: [PrimitivesInput$Ref],
        required: { list: true, items: true },
        description: "Required.",
        extensions: {
          protobufField: {
            name: "required_primitives_list",
            typeFullName: "testapis.basic.scalars.Primitives",
          },
        },
      }),
      optionalPrimitivesList: t.field({
        type: [PrimitivesInput$Ref],
        required: { list: false, items: true },
        description: "Optional.",
        extensions: {
          protobufField: {
            name: "optional_primitives_list",
            typeFullName: "testapis.basic.scalars.Primitives",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.basic.scalars.Message",
        name: "Message",
        package: "testapis.basic.scalars",
      },
    },
  });

export type PrimitivesInput$Shape = {
  requiredDoubleValue: Primitives["requiredDoubleValue"];
  requiredFloatValue: Primitives["requiredFloatValue"];
  requiredInt32Value: Primitives["requiredInt32Value"];
  requiredInt64Value: Primitives["requiredInt64Value"];
  requiredUint32Value: Primitives["requiredUint32Value"];
  requiredUint64Value: Primitives["requiredUint64Value"];
  requiredSint32Value: Primitives["requiredSint32Value"];
  requiredSint64Value: Primitives["requiredSint64Value"];
  requiredFixed32Value: Primitives["requiredFixed32Value"];
  requiredFixed64Value: Primitives["requiredFixed64Value"];
  requiredSfixed32Value: Primitives["requiredSfixed32Value"];
  requiredSfixed64Value: Primitives["requiredSfixed64Value"];
  requiredBoolValue: Primitives["requiredBoolValue"];
  requiredStringValue: Primitives["requiredStringValue"];
  requiredBytesValue: Primitives["requiredBytesValue"];
  requiredDoubleValues: Primitives["requiredDoubleValues"];
  requiredFloatValues: Primitives["requiredFloatValues"];
  requiredInt32Values: Primitives["requiredInt32Values"];
  requiredInt64Values: Primitives["requiredInt64Values"];
  requiredUint32Values: Primitives["requiredUint32Values"];
  requiredUint64Values: Primitives["requiredUint64Values"];
  requiredSint32Values: Primitives["requiredSint32Values"];
  requiredSint64Values: Primitives["requiredSint64Values"];
  requiredFixed32Values: Primitives["requiredFixed32Values"];
  requiredFixed64Values: Primitives["requiredFixed64Values"];
  requiredSfixed32Values: Primitives["requiredSfixed32Values"];
  requiredSfixed64Values: Primitives["requiredSfixed64Values"];
  requiredBoolValues: Primitives["requiredBoolValues"];
  requiredStringValues: Primitives["requiredStringValues"];
  requiredBytesValues: Primitives["requiredBytesValues"];
};

export const PrimitivesInput$Ref: InputObjectRef<PrimitivesInput$Shape> =
  builder.inputRef<PrimitivesInput$Shape>("PrimitivesInput").implement({
    fields: (t) => ({
      requiredDoubleValue: t.field({
        type: "Float",
        required: true,
        extensions: {
          protobufField: {
            name: "required_double_value",
            typeFullName: "double",
          },
        },
      }),
      requiredFloatValue: t.field({
        type: "Float",
        required: true,
        extensions: {
          protobufField: {
            name: "required_float_value",
            typeFullName: "float",
          },
        },
      }),
      requiredInt32Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_int32_value",
            typeFullName: "int32",
          },
        },
      }),
      requiredInt64Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_int64_value",
            typeFullName: "int64",
          },
        },
      }),
      requiredUint32Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_uint32_value",
            typeFullName: "uint32",
          },
        },
      }),
      requiredUint64Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_uint64_value",
            typeFullName: "uint64",
          },
        },
      }),
      requiredSint32Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_sint32_value",
            typeFullName: "sint32",
          },
        },
      }),
      requiredSint64Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_sint64_value",
            typeFullName: "sint64",
          },
        },
      }),
      requiredFixed32Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_fixed32_value",
            typeFullName: "fixed32",
          },
        },
      }),
      requiredFixed64Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_fixed64_value",
            typeFullName: "fixed64",
          },
        },
      }),
      requiredSfixed32Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_sfixed32_value",
            typeFullName: "sfixed32",
          },
        },
      }),
      requiredSfixed64Value: t.field({
        type: "Int",
        required: true,
        extensions: {
          protobufField: {
            name: "required_sfixed64_value",
            typeFullName: "sfixed64",
          },
        },
      }),
      requiredBoolValue: t.field({
        type: "Boolean",
        required: true,
        extensions: {
          protobufField: { name: "required_bool_value", typeFullName: "bool" },
        },
      }),
      requiredStringValue: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: {
            name: "required_string_value",
            typeFullName: "string",
          },
        },
      }),
      requiredBytesValue: t.field({
        type: "Byte",
        required: true,
        extensions: {
          protobufField: {
            name: "required_bytes_value",
            typeFullName: "bytes",
          },
        },
      }),
      requiredDoubleValues: t.field({
        type: ["Float"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_double_values",
            typeFullName: "double",
          },
        },
      }),
      requiredFloatValues: t.field({
        type: ["Float"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_float_values",
            typeFullName: "float",
          },
        },
      }),
      requiredInt32Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_int32_values",
            typeFullName: "int32",
          },
        },
      }),
      requiredInt64Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_int64_values",
            typeFullName: "int64",
          },
        },
      }),
      requiredUint32Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_uint32_values",
            typeFullName: "uint32",
          },
        },
      }),
      requiredUint64Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_uint64_values",
            typeFullName: "uint64",
          },
        },
      }),
      requiredSint32Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_sint32_values",
            typeFullName: "sint32",
          },
        },
      }),
      requiredSint64Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_sint64_values",
            typeFullName: "sint64",
          },
        },
      }),
      requiredFixed32Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_fixed32_values",
            typeFullName: "fixed32",
          },
        },
      }),
      requiredFixed64Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_fixed64_values",
            typeFullName: "fixed64",
          },
        },
      }),
      requiredSfixed32Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_sfixed32_values",
            typeFullName: "sfixed32",
          },
        },
      }),
      requiredSfixed64Values: t.field({
        type: ["Int"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_sfixed64_values",
            typeFullName: "sfixed64",
          },
        },
      }),
      requiredBoolValues: t.field({
        type: ["Boolean"],
        required: { list: true, items: true },
        extensions: {
          protobufField: { name: "required_bool_values", typeFullName: "bool" },
        },
      }),
      requiredStringValues: t.field({
        type: ["String"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_string_values",
            typeFullName: "string",
          },
        },
      }),
      requiredBytesValues: t.field({
        type: ["Byte"],
        required: { list: true, items: true },
        extensions: {
          protobufField: {
            name: "required_bytes_values",
            typeFullName: "bytes",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.basic.scalars.Primitives",
        name: "Primitives",
        package: "testapis.basic.scalars",
      },
    },
  });
