// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es-v1"
// @generated from file testapis/oneof/oneof.proto (package testapis.oneof, syntax proto3)
/* eslint-disable */

import { builder } from "../../../builder";
import {
  OneofMemberMessage1,
  OneofMemberMessage2,
  OneofParent,
} from "@proto-graphql/e2e-testapis-protobuf-es/lib/testapis/oneof/oneof_pb";
import { InputObjectRef } from "@pothos/core";

export const OneofParent$Ref = builder.objectRef<OneofParent>("OneofParent");
builder.objectType(OneofParent$Ref, {
  name: "OneofParent",
  fields: (t) => ({
    normalField: t.expose("normalField", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "normal_field", typeFullName: "string" },
      },
    }),
    requiredOneofMembers: t.field({
      type: OneofParentRequiredOneofMembers$Ref,
      nullable: false,
      description: "Required. disallow not_set.",
      resolve: (source) => {
        const value = source.requiredOneofMembers.value as
          | OneofMemberMessage1
          | OneofMemberMessage2
          | undefined;
        if (value == null) {
          throw new Error("requiredOneofMembers should not be null");
        }
        return value;
      },
      extensions: { protobufField: { name: "required_oneof_members" } },
    }),
    optionalOneofMembers: t.field({
      type: OneofParentOptionalOneofMembers$Ref,
      nullable: true,
      resolve: (source) => {
        return (source.optionalOneofMembers.value ?? null) as
          | OneofMemberMessage1
          | OneofMemberMessage2
          | undefined
          | null;
      },
      extensions: { protobufField: { name: "optional_oneof_members" } },
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof OneofParent;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.oneof.OneofParent",
      name: "OneofParent",
      package: "testapis.oneof",
    },
  },
});

export const OneofMemberMessage1$Ref = builder.objectRef<OneofMemberMessage1>(
  "OneofMemberMessage1",
);
builder.objectType(OneofMemberMessage1$Ref, {
  name: "OneofMemberMessage1",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof OneofMemberMessage1;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.oneof.OneofMemberMessage1",
      name: "OneofMemberMessage1",
      package: "testapis.oneof",
    },
  },
});

export const OneofMemberMessage2$Ref = builder.objectRef<OneofMemberMessage2>(
  "OneofMemberMessage2",
);
builder.objectType(OneofMemberMessage2$Ref, {
  name: "OneofMemberMessage2",
  fields: (t) => ({
    imageUrl: t.expose("imageUrl", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "image_url", typeFullName: "string" },
      },
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof OneofMemberMessage2;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.oneof.OneofMemberMessage2",
      name: "OneofMemberMessage2",
      package: "testapis.oneof",
    },
  },
});

export type OneofParentInput$Shape = {
  normalField: OneofParent["normalField"];
  requiredMessage1?: OneofMemberMessage1Input$Shape | null;
  requiredMessage2?: OneofMemberMessage2Input$Shape | null;
  optoinalMessage1?: OneofMemberMessage1Input$Shape | null;
  optoinalMessage2?: OneofMemberMessage2Input$Shape | null;
};

export const OneofParentInput$Ref: InputObjectRef<OneofParentInput$Shape> =
  builder.inputRef<OneofParentInput$Shape>("OneofParentInput").implement({
    fields: (t) => ({
      normalField: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "normal_field", typeFullName: "string" },
        },
      }),
      requiredMessage1: t.field({
        type: OneofMemberMessage1Input$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "required_message1",
            typeFullName: "testapis.oneof.OneofMemberMessage1",
          },
        },
      }),
      requiredMessage2: t.field({
        type: OneofMemberMessage2Input$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "required_message2",
            typeFullName: "testapis.oneof.OneofMemberMessage2",
          },
        },
      }),
      optoinalMessage1: t.field({
        type: OneofMemberMessage1Input$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "optoinal_message1",
            typeFullName: "testapis.oneof.OneofMemberMessage1",
          },
        },
      }),
      optoinalMessage2: t.field({
        type: OneofMemberMessage2Input$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "optoinal_message2",
            typeFullName: "testapis.oneof.OneofMemberMessage2",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.oneof.OneofParent",
        name: "OneofParent",
        package: "testapis.oneof",
      },
    },
  });

export function OneofParentInput$toProto(
  input: OneofParentInput$Shape | null | undefined,
): OneofParent {
  return new OneofParent({
    normalField: input?.normalField ?? undefined,
    requiredOneofMembers: input?.requiredMessage1
      ? {
        case: "requiredMessage1",
        value: OneofMemberMessage1Input$toProto(input.requiredMessage1),
      }
      : input?.requiredMessage2
      ? {
        case: "requiredMessage2",
        value: OneofMemberMessage2Input$toProto(input.requiredMessage2),
      }
      : undefined,
    optionalOneofMembers: input?.optoinalMessage1
      ? {
        case: "optoinalMessage1",
        value: OneofMemberMessage1Input$toProto(input.optoinalMessage1),
      }
      : input?.optoinalMessage2
      ? {
        case: "optoinalMessage2",
        value: OneofMemberMessage2Input$toProto(input.optoinalMessage2),
      }
      : undefined,
  });
}

export type OneofMemberMessage1Input$Shape = {
  body: OneofMemberMessage1["body"];
};

export const OneofMemberMessage1Input$Ref: InputObjectRef<
  OneofMemberMessage1Input$Shape
> = builder.inputRef<OneofMemberMessage1Input$Shape>("OneofMemberMessage1Input")
  .implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.oneof.OneofMemberMessage1",
        name: "OneofMemberMessage1",
        package: "testapis.oneof",
      },
    },
  });

export function OneofMemberMessage1Input$toProto(
  input: OneofMemberMessage1Input$Shape | null | undefined,
): OneofMemberMessage1 {
  return new OneofMemberMessage1({ body: input?.body ?? undefined });
}

export type OneofMemberMessage2Input$Shape = {
  imageUrl: OneofMemberMessage2["imageUrl"];
};

export const OneofMemberMessage2Input$Ref: InputObjectRef<
  OneofMemberMessage2Input$Shape
> = builder.inputRef<OneofMemberMessage2Input$Shape>("OneofMemberMessage2Input")
  .implement({
    fields: (t) => ({
      imageUrl: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "image_url", typeFullName: "string" },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.oneof.OneofMemberMessage2",
        name: "OneofMemberMessage2",
        package: "testapis.oneof",
      },
    },
  });

export function OneofMemberMessage2Input$toProto(
  input: OneofMemberMessage2Input$Shape | null | undefined,
): OneofMemberMessage2 {
  return new OneofMemberMessage2({ imageUrl: input?.imageUrl ?? undefined });
}

export const OneofParentRequiredOneofMembers$Ref = builder.unionType(
  "OneofParentRequiredOneofMembers",
  {
    types: [OneofMemberMessage1$Ref, OneofMemberMessage2$Ref],
    description: "Required. disallow not_set.",
    extensions: {
      protobufOneof: {
        fullName: "testapis.oneof.OneofParent.required_oneof_members",
        name: "required_oneof_members",
        messageName: "OneofParent",
        package: "testapis.oneof",
        fields: [{
          name: "required_message1",
          type: "testapis.oneof.OneofMemberMessage1",
        }, {
          name: "required_message2",
          type: "testapis.oneof.OneofMemberMessage2",
        }],
      },
    },
  },
);

export const OneofParentOptionalOneofMembers$Ref = builder.unionType(
  "OneofParentOptionalOneofMembers",
  {
    types: [OneofMemberMessage1$Ref, OneofMemberMessage2$Ref],
    extensions: {
      protobufOneof: {
        fullName: "testapis.oneof.OneofParent.optional_oneof_members",
        name: "optional_oneof_members",
        messageName: "OneofParent",
        package: "testapis.oneof",
        fields: [{
          name: "optoinal_message1",
          type: "testapis.oneof.OneofMemberMessage1",
        }, {
          name: "optoinal_message2",
          type: "testapis.oneof.OneofMemberMessage2",
        }],
      },
    },
  },
);
