// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: testapis/edgecases/import_squashed_union/pkg1/types.proto

/* eslint-disable */

import * as $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb from "@testapis/node-native/lib//testapis/edgecases/import_squashed_union/pkg1/types_pb";
import * as nexus from "nexus";
import * as proto_nexus from "proto-nexus";
export type $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb$OneofMessage1 = $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb.OneofMessage1;
export const OneofMessage1 = nexus.objectType({
    name: "OneofMessage1",
    definition(t) {
        t.field("body", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getBody();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "body"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    isTypeOf(data: unknown) {
        return data instanceof $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb.OneofMessage1;
    },
    sourceType: { module: __filename, export: "$$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb$OneofMessage1" },
    extensions: {
        ...({
            protobufMessage: {
                fullName: "testapis.edgecases.import_squashed_union.pkg1.OneofMessage1",
                name: "OneofMessage1",
                package: "testapis.edgecases.import_squashed_union.pkg1"
            }
        } as proto_nexus.ProtobufMessageExtensions)
    }
});
export const OneofMessage1Input = Object.assign(nexus.inputObjectType({
    name: "OneofMessage1Input",
    definition(t) {
        t.field("body", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "body"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    extensions: {
        protobufMessage: {
            fullName: "testapis.edgecases.import_squashed_union.pkg1.OneofMessage1",
            name: "OneofMessage1",
            package: "testapis.edgecases.import_squashed_union.pkg1"
        }
    }
}), {
    toProto: (input: NexusGen["inputTypes"]["OneofMessage1Input"]): $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb.OneofMessage1 => {
        const output = new $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb.OneofMessage1();
        output.setBody(input.body);
        return output;
    },
    _protoNexus: {
        fields: {
            body: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "body"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            }
        }
    }
});
export const SquashedOneofInput = Object.assign(nexus.inputObjectType({
    name: "SquashedOneofInput",
    definition(t) {
        t.field("msg1", {
            type: nexus.nullable("OneofMessage1Input"),
            extensions: {
                ...({
                    protobufField: {
                        name: "msg1"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    extensions: {
        protobufMessage: {
            fullName: "testapis.edgecases.import_squashed_union.pkg1.SquashedOneof",
            name: "SquashedOneof",
            package: "testapis.edgecases.import_squashed_union.pkg1"
        }
    }
}), {
    toProto: (input: NexusGen["inputTypes"]["SquashedOneofInput"]): $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb.SquashedOneof => {
        const output = new $$testapis$node_native$lib$$testapis$edgecases$import_squashed_union$pkg1$types_pb.SquashedOneof();
        if (input.msg1 != null) {
            output.setMsg1(OneofMessage1Input.toProto(input.msg1));
        }
        return output;
    },
    _protoNexus: {
        fields: {
            msg1: {
                type: nexus.nullable("OneofMessage1Input"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "msg1"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            }
        }
    }
});
export const SquashedOneof = nexus.unionType({
    name: "SquashedOneof",
    definition(t) {
        t.members(OneofMessage1);
    },
    extensions: {
        ...({
            protobufMessage: {
                fullName: "testapis.edgecases.import_squashed_union.pkg1.SquashedOneof",
                name: "SquashedOneof",
                package: "testapis.edgecases.import_squashed_union.pkg1",
                fields: [
                    {
                        name: "msg1",
                        type: "testapis.edgecases.import_squashed_union.pkg1.OneofMessage1"
                    }
                ]
            }
        } as proto_nexus.ProtobufMessageExtensions)
    }
});
