// source: testapis/deprecation/file_deprecation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.testapis.deprecation.DeprecatedFileEnum', null, global);
goog.exportSymbol('proto.testapis.deprecation.DeprecatedFileMessage', null, global);
goog.exportSymbol('proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.testapis.deprecation.DeprecatedFileMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.testapis.deprecation.DeprecatedFileMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.testapis.deprecation.DeprecatedFileMessage.displayName = 'proto.testapis.deprecation.DeprecatedFileMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.displayName = 'proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.testapis.deprecation.DeprecatedFileMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.testapis.deprecation.DeprecatedFileMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.testapis.deprecation.DeprecatedFileMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.testapis.deprecation.DeprecatedFileMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    body: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pb_enum: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.testapis.deprecation.DeprecatedFileMessage}
 */
proto.testapis.deprecation.DeprecatedFileMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.testapis.deprecation.DeprecatedFileMessage;
  return proto.testapis.deprecation.DeprecatedFileMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.testapis.deprecation.DeprecatedFileMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.testapis.deprecation.DeprecatedFileMessage}
 */
proto.testapis.deprecation.DeprecatedFileMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 2:
      var value = /** @type {!proto.testapis.deprecation.DeprecatedFileEnum} */ (reader.readEnum());
      msg.setEnum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.testapis.deprecation.DeprecatedFileMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.testapis.deprecation.DeprecatedFileMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.testapis.deprecation.DeprecatedFileMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.testapis.deprecation.DeprecatedFileMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEnum();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    body: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage}
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage;
  return proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage}
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string body = 1;
 * @return {string}
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage} returns this
 */
proto.testapis.deprecation.DeprecatedFileMessage.InnerMessage.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string body = 1;
 * @return {string}
 */
proto.testapis.deprecation.DeprecatedFileMessage.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.testapis.deprecation.DeprecatedFileMessage} returns this
 */
proto.testapis.deprecation.DeprecatedFileMessage.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional DeprecatedFileEnum enum = 2;
 * @return {!proto.testapis.deprecation.DeprecatedFileEnum}
 */
proto.testapis.deprecation.DeprecatedFileMessage.prototype.getEnum = function() {
  return /** @type {!proto.testapis.deprecation.DeprecatedFileEnum} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.testapis.deprecation.DeprecatedFileEnum} value
 * @return {!proto.testapis.deprecation.DeprecatedFileMessage} returns this
 */
proto.testapis.deprecation.DeprecatedFileMessage.prototype.setEnum = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.testapis.deprecation.DeprecatedFileEnum = {
  DEPRECATED_FILE_ENUM_UNSPECIFIED: 0,
  DEPRECATED_FILE_FOO: 1,
  DEPRECATED_FILE_BAR: 2
};

goog.object.extend(exports, proto.testapis.deprecation);
