// @generated by protoc-gen-pothos v0.7.0 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es-v1"
// @generated from file testapis/options/field_nullability/field_nullability.proto (package testapis.options.field_nullability, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import {
  Message,
  Message_Status,
} from "@proto-graphql/e2e-testapis-protobuf-es/lib/testapis/options/field_nullability/field_nullability_pb";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const Message$Ref = builder.objectRef<Message>("Message");
builder.objectType(Message$Ref, {
  name: "Message",
  fields: (t) => ({
    userId: t.expose("userId", {
      type: "Int64",
      nullable: false,
      description: "Required.",
      extensions: {
        protobufField: {
          name: "user_id",
          typeFullName: "uint64",
          options: {
            "[graphql.field]": {
              outputNullability: "NON_NULL",
              inputNullability: "NULLABLE",
              partialInputNullability: "NON_NULL",
            },
          },
        },
      },
    }),
    body: t.expose("body", {
      type: "String",
      nullable: false,
      description: "Required.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
    status: t.field({
      type: MessageStatus$Ref,
      nullable: true,
      description: "Required.",
      resolve: (source) => {
        if (source.status === Message_Status.STATUS_UNSPECIFIED) {
          return null;
        }

        return source.status;
      },
      extensions: {
        protobufField: {
          name: "status",
          typeFullName: "testapis.options.field_nullability.Message.Status",
          options: {
            "[graphql.field]": {
              outputNullability: "NULLABLE",
              inputNullability: "NULLABLE",
            },
          },
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof Message;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.options.field_nullability.Message",
      name: "Message",
      package: "testapis.options.field_nullability",
    },
  },
});

export type MessageInput$Shape = {
  userId?: Message["userId"] | null;
  body: Message["body"];
  status?: Message["status"] | null;
};

export const MessageInput$Ref: InputObjectRef<MessageInput$Shape> = builder
  .inputRef<MessageInput$Shape>("MessageInput").implement({
    fields: (t) => ({
      userId: t.field({
        type: "Int64",
        required: false,
        description: "Required.",
        extensions: {
          protobufField: {
            name: "user_id",
            typeFullName: "uint64",
            options: {
              "[graphql.field]": {
                outputNullability: "NON_NULL",
                inputNullability: "NULLABLE",
                partialInputNullability: "NON_NULL",
              },
            },
          },
        },
      }),
      body: t.field({
        type: "String",
        required: true,
        description: "Required.",
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
      status: t.field({
        type: MessageStatus$Ref,
        required: false,
        description: "Required.",
        extensions: {
          protobufField: {
            name: "status",
            typeFullName: "testapis.options.field_nullability.Message.Status",
            options: {
              "[graphql.field]": {
                outputNullability: "NULLABLE",
                inputNullability: "NULLABLE",
              },
            },
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.options.field_nullability.Message",
        name: "Message",
        package: "testapis.options.field_nullability",
      },
    },
  });

export function MessageInput$toProto(
  input: MessageInput$Shape | null | undefined,
): Message {
  return new Message({
    userId: input?.userId ?? undefined,
    body: input?.body ?? undefined,
    status: input?.status ?? undefined,
  });
}

export const MessageStatus$Ref: EnumRef<Message_Status, Message_Status> =
  builder.enumType("MessageStatus", {
    values: {
      DRAFT: { value: 1, extensions: { protobufEnumValue: { name: "DRAFT" } } },
      PUBLISHED: {
        value: 2,
        extensions: { protobufEnumValue: { name: "PUBLISHED" } },
      },
    } as const,
    extensions: {
      protobufEnum: {
        name: "Status",
        fullName: "testapis.options.field_nullability.Message.Status",
        package: "testapis.options.field_nullability",
      },
    },
  });
