// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: testapis/multipkgs/subpkg1/types.proto

/* eslint-disable */

import * as $$testapis$node_native$lib$$testapis$multipkgs$subpkg1$types_pb from "@testapis/node-native/lib//testapis/multipkgs/subpkg1/types_pb";
import * as nexus from "nexus";
import * as proto_nexus from "proto-nexus";
export type $$testapis$node_native$lib$$testapis$multipkgs$subpkg1$types_pb$SubpkgMessage = $$testapis$node_native$lib$$testapis$multipkgs$subpkg1$types_pb.SubpkgMessage;
export const SubpkgMessage = nexus.objectType({
    name: "SubpkgMessage",
    definition(t) {
        t.field("body", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getBody();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "body"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    isTypeOf(data: unknown) {
        return data instanceof $$testapis$node_native$lib$$testapis$multipkgs$subpkg1$types_pb.SubpkgMessage;
    },
    sourceType: { module: __filename, export: "$$testapis$node_native$lib$$testapis$multipkgs$subpkg1$types_pb$SubpkgMessage" },
    extensions: {
        ...({
            protobufMessage: {
                fullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
                name: "SubpkgMessage",
                package: "testapis.multipkgs.subpkg1"
            }
        } as proto_nexus.ProtobufMessageExtensions)
    }
});
export const SubpkgMessageInput = Object.assign(nexus.inputObjectType({
    name: "SubpkgMessageInput",
    definition(t) {
        t.field("body", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "body"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    extensions: {
        protobufMessage: {
            fullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
            name: "SubpkgMessage",
            package: "testapis.multipkgs.subpkg1"
        }
    }
}), {
    toProto: (input: NexusGen["inputTypes"]["SubpkgMessageInput"]): $$testapis$node_native$lib$$testapis$multipkgs$subpkg1$types_pb.SubpkgMessage => {
        const output = new $$testapis$node_native$lib$$testapis$multipkgs$subpkg1$types_pb.SubpkgMessage();
        output.setBody(input.body);
        return output;
    },
    _protoNexus: {
        fields: {
            body: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "body"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            }
        }
    }
});
export const SubpkgEnum = nexus.enumType({
    name: "SubpkgEnum",
    members: [
        {
            name: "FOO",
            value: 1,
            extensions: {
                ...({
                    protobufEnumValue: {
                        name: "FOO"
                    }
                } as proto_nexus.ProtobufEnumValueExtensions)
            }
        },
        {
            name: "BAR",
            value: 2,
            extensions: {
                ...({
                    protobufEnumValue: {
                        name: "BAR"
                    }
                } as proto_nexus.ProtobufEnumValueExtensions)
            }
        }
    ],
    extensions: {
        ...({
            protobufEnum: {
                name: "SubpkgEnum",
                fullName: "testapis.multipkgs.subpkg1.SubpkgEnum",
                package: "testapis.multipkgs.subpkg1"
            }
        } as proto_nexus.ProtobufEnumExtensions)
    }
});
