// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: testapis/extensions/field_nullability/nullability.proto

/* eslint-disable */

import * as $$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb from "@testapis/node-native/lib//testapis/extensions/field_nullability/nullability_pb";
import * as nexus from "nexus";
import * as proto_nexus from "proto-nexus";
export type $$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb$Message = $$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb.Message;
export const Message = nexus.objectType({
    name: "Message",
    definition(t) {
        t.field("userId", {
            type: nexus.nonNull("String"),
            description: "Required.",
            resolve(root) {
                const value = root.getUserId();
                return value.toString();
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "user_id"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("body", {
            type: nexus.nonNull("String"),
            description: "Required.",
            resolve(root) {
                const value = root.getBody();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "body"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("status", {
            type: nexus.nullable("MessageStatus"),
            description: "Required.",
            resolve(root) {
                const value = root.getStatus();
                if (value == null) {
                    return null;
                }
                if (value === $$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb.Message.Status.STATUS_UNSPECIFIED) {
                    return null;
                }
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "status"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    isTypeOf(data: unknown) {
        return data instanceof $$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb.Message;
    },
    sourceType: { module: __filename, export: "$$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb$Message" },
    extensions: {
        ...({
            protobufMessage: {
                fullName: "testapis.extensions.field_nullability.Message",
                name: "Message",
                package: "testapis.extensions.field_nullability"
            }
        } as proto_nexus.ProtobufMessageExtensions)
    }
});
export const MessageInput = Object.assign(nexus.inputObjectType({
    name: "MessageInput",
    definition(t) {
        t.field("userId", {
            type: nexus.nullable("String"),
            description: "Required.",
            extensions: {
                ...({
                    protobufField: {
                        name: "user_id"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("body", {
            type: nexus.nonNull("String"),
            description: "Required.",
            extensions: {
                ...({
                    protobufField: {
                        name: "body"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("status", {
            type: nexus.nullable("MessageStatus"),
            description: "Required.",
            extensions: {
                ...({
                    protobufField: {
                        name: "status"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    extensions: {
        protobufMessage: {
            fullName: "testapis.extensions.field_nullability.Message",
            name: "Message",
            package: "testapis.extensions.field_nullability"
        }
    }
}), {
    toProto: (input: NexusGen["inputTypes"]["MessageInput"]): $$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb.Message => {
        const output = new $$testapis$node_native$lib$$testapis$extensions$field_nullability$nullability_pb.Message();
        if (input.userId != null) {
            output.setUserId(proto_nexus.stringToNumber(input.userId));
        }
        output.setBody(input.body);
        if (input.status != null) {
            output.setStatus(input.status);
        }
        return output;
    },
    _protoNexus: {
        fields: {
            userId: {
                type: nexus.nullable("String"),
                description: "Required.",
                extensions: {
                    ...({
                        protobufField: {
                            name: "user_id"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            body: {
                type: nexus.nonNull("String"),
                description: "Required.",
                extensions: {
                    ...({
                        protobufField: {
                            name: "body"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            status: {
                type: nexus.nullable("MessageStatus"),
                description: "Required.",
                extensions: {
                    ...({
                        protobufField: {
                            name: "status"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            }
        }
    }
});
export const MessageStatus = nexus.enumType({
    name: "MessageStatus",
    members: [
        {
            name: "DRAFT",
            value: 1,
            extensions: {
                ...({
                    protobufEnumValue: {
                        name: "DRAFT"
                    }
                } as proto_nexus.ProtobufEnumValueExtensions)
            }
        },
        {
            name: "PUBLISHED",
            value: 2,
            extensions: {
                ...({
                    protobufEnumValue: {
                        name: "PUBLISHED"
                    }
                } as proto_nexus.ProtobufEnumValueExtensions)
            }
        }
    ],
    extensions: {
        ...({
            protobufEnum: {
                name: "Status",
                fullName: "testapis.extensions.field_nullability.Message.Status",
                package: "testapis.extensions.field_nullability"
            }
        } as proto_nexus.ProtobufEnumExtensions)
    }
});
