// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: testapis/primitives/primitives.proto

/* eslint-disable */

import * as $$testapis$node_native$lib$$testapis$primitives$primitives_pb from "@testapis/node-native/lib//testapis/primitives/primitives_pb";
import * as nexus from "nexus";
import * as proto_nexus from "proto-nexus";
export type $$testapis$node_native$lib$$testapis$primitives$primitives_pb$Message = $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Message;
export type $$testapis$node_native$lib$$testapis$primitives$primitives_pb$Primitives = $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Primitives;
export const Message = nexus.objectType({
    name: "Message",
    definition(t) {
        t.field("requiredPrimitives", {
            type: nexus.nonNull("Primitives"),
            description: "Required.",
            resolve(root) {
                const value = root.getRequiredPrimitives();
                if (value == null) {
                    throw new Error("Cannot return null for non-nullable field");
                }
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_primitives"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("optionalPrimitives", {
            type: nexus.nullable("Primitives"),
            description: "Optional.",
            resolve(root) {
                const value = root.getOptionalPrimitives();
                if (value == null) {
                    return null;
                }
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "optional_primitives"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredPrimitivesList", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Primitives"))),
            description: "Required.",
            resolve(root) {
                const value = root.getRequiredPrimitivesListList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_primitives_list"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("optionalPrimitivesList", {
            type: nexus.nullable(nexus.list(nexus.nonNull("Primitives"))),
            description: "Optional.",
            resolve(root) {
                const value = root.getOptionalPrimitivesListList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "optional_primitives_list"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    isTypeOf(data: unknown) {
        return data instanceof $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Message;
    },
    sourceType: { module: __filename, export: "$$testapis$node_native$lib$$testapis$primitives$primitives_pb$Message" },
    extensions: {
        ...({
            protobufMessage: {
                fullName: "testapis.primitives.Message",
                name: "Message",
                package: "testapis.primitives"
            }
        } as proto_nexus.ProtobufMessageExtensions)
    }
});
export const Primitives = nexus.objectType({
    name: "Primitives",
    definition(t) {
        t.field("requiredDoubleValue", {
            type: nexus.nonNull("Float"),
            resolve(root) {
                const value = root.getRequiredDoubleValue();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_double_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFloatValue", {
            type: nexus.nonNull("Float"),
            resolve(root) {
                const value = root.getRequiredFloatValue();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_float_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt32Value", {
            type: nexus.nonNull("Int"),
            resolve(root) {
                const value = root.getRequiredInt32Value();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt64Value", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getRequiredInt64Value();
                return value.toString();
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint32Value", {
            type: nexus.nonNull("Int"),
            resolve(root) {
                const value = root.getRequiredUint32Value();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint64Value", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getRequiredUint64Value();
                return value.toString();
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint32Value", {
            type: nexus.nonNull("Int"),
            resolve(root) {
                const value = root.getRequiredSint32Value();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint64Value", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getRequiredSint64Value();
                return value.toString();
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed32Value", {
            type: nexus.nonNull("Int"),
            resolve(root) {
                const value = root.getRequiredFixed32Value();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed64Value", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getRequiredFixed64Value();
                return value.toString();
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed32Value", {
            type: nexus.nonNull("Int"),
            resolve(root) {
                const value = root.getRequiredSfixed32Value();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed64Value", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getRequiredSfixed64Value();
                return value.toString();
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredBoolValue", {
            type: nexus.nonNull("Boolean"),
            resolve(root) {
                const value = root.getRequiredBoolValue();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_bool_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredStringValue", {
            type: nexus.nonNull("String"),
            resolve(root) {
                const value = root.getRequiredStringValue();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_string_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredDoubleValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Float"))),
            resolve(root) {
                const value = root.getRequiredDoubleValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_double_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFloatValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Float"))),
            resolve(root) {
                const value = root.getRequiredFloatValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_float_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            resolve(root) {
                const value = root.getRequiredInt32ValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            resolve(root) {
                const value = root.getRequiredInt64ValuesList();
                return value.map(item => {
                    return item.toString();
                });
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            resolve(root) {
                const value = root.getRequiredUint32ValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            resolve(root) {
                const value = root.getRequiredUint64ValuesList();
                return value.map(item => {
                    return item.toString();
                });
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            resolve(root) {
                const value = root.getRequiredSint32ValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            resolve(root) {
                const value = root.getRequiredSint64ValuesList();
                return value.map(item => {
                    return item.toString();
                });
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            resolve(root) {
                const value = root.getRequiredFixed32ValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            resolve(root) {
                const value = root.getRequiredFixed64ValuesList();
                return value.map(item => {
                    return item.toString();
                });
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            resolve(root) {
                const value = root.getRequiredSfixed32ValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            resolve(root) {
                const value = root.getRequiredSfixed64ValuesList();
                return value.map(item => {
                    return item.toString();
                });
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredBoolValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Boolean"))),
            resolve(root) {
                const value = root.getRequiredBoolValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_bool_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredStringValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            resolve(root) {
                const value = root.getRequiredStringValuesList();
                return value;
            },
            extensions: {
                ...({
                    protobufField: {
                        name: "required_string_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    isTypeOf(data: unknown) {
        return data instanceof $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Primitives;
    },
    sourceType: { module: __filename, export: "$$testapis$node_native$lib$$testapis$primitives$primitives_pb$Primitives" },
    extensions: {
        ...({
            protobufMessage: {
                fullName: "testapis.primitives.Primitives",
                name: "Primitives",
                package: "testapis.primitives"
            }
        } as proto_nexus.ProtobufMessageExtensions)
    }
});
export const MessageInput = Object.assign(nexus.inputObjectType({
    name: "MessageInput",
    definition(t) {
        t.field("requiredPrimitives", {
            type: nexus.nonNull("PrimitivesInput"),
            description: "Required.",
            extensions: {
                ...({
                    protobufField: {
                        name: "required_primitives"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("optionalPrimitives", {
            type: nexus.nullable("PrimitivesInput"),
            description: "Optional.",
            extensions: {
                ...({
                    protobufField: {
                        name: "optional_primitives"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredPrimitivesList", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("PrimitivesInput"))),
            description: "Required.",
            extensions: {
                ...({
                    protobufField: {
                        name: "required_primitives_list"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("optionalPrimitivesList", {
            type: nexus.nullable(nexus.list(nexus.nonNull("PrimitivesInput"))),
            description: "Optional.",
            extensions: {
                ...({
                    protobufField: {
                        name: "optional_primitives_list"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    extensions: {
        protobufMessage: {
            fullName: "testapis.primitives.Message",
            name: "Message",
            package: "testapis.primitives"
        }
    }
}), {
    toProto: (input: NexusGen["inputTypes"]["MessageInput"]): $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Message => {
        const output = new $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Message();
        output.setRequiredPrimitives(PrimitivesInput.toProto(input.requiredPrimitives));
        if (input.optionalPrimitives != null) {
            output.setOptionalPrimitives(PrimitivesInput.toProto(input.optionalPrimitives));
        }
        output.setRequiredPrimitivesListList(input.requiredPrimitivesList.map(v => PrimitivesInput.toProto(v)));
        if (input.optionalPrimitivesList != null) {
            output.setOptionalPrimitivesListList(input.optionalPrimitivesList.map(v => PrimitivesInput.toProto(v)));
        }
        return output;
    },
    _protoNexus: {
        fields: {
            requiredPrimitives: {
                type: nexus.nonNull("PrimitivesInput"),
                description: "Required.",
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_primitives"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            optionalPrimitives: {
                type: nexus.nullable("PrimitivesInput"),
                description: "Optional.",
                extensions: {
                    ...({
                        protobufField: {
                            name: "optional_primitives"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredPrimitivesList: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("PrimitivesInput"))),
                description: "Required.",
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_primitives_list"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            optionalPrimitivesList: {
                type: nexus.nullable(nexus.list(nexus.nonNull("PrimitivesInput"))),
                description: "Optional.",
                extensions: {
                    ...({
                        protobufField: {
                            name: "optional_primitives_list"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            }
        }
    }
});
export const PrimitivesInput = Object.assign(nexus.inputObjectType({
    name: "PrimitivesInput",
    definition(t) {
        t.field("requiredDoubleValue", {
            type: nexus.nonNull("Float"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_double_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFloatValue", {
            type: nexus.nonNull("Float"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_float_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt32Value", {
            type: nexus.nonNull("Int"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt64Value", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint32Value", {
            type: nexus.nonNull("Int"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint64Value", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint32Value", {
            type: nexus.nonNull("Int"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint64Value", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed32Value", {
            type: nexus.nonNull("Int"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed64Value", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed32Value", {
            type: nexus.nonNull("Int"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed32_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed64Value", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed64_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredBoolValue", {
            type: nexus.nonNull("Boolean"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_bool_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredStringValue", {
            type: nexus.nonNull("String"),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_string_value"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredDoubleValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Float"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_double_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFloatValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Float"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_float_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredInt64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_int64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredUint64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_uint64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSint64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sint64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredFixed64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_fixed64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed32Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed32_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredSfixed64Values", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_sfixed64_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredBoolValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("Boolean"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_bool_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
        t.field("requiredStringValues", {
            type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
            extensions: {
                ...({
                    protobufField: {
                        name: "required_string_values"
                    }
                } as proto_nexus.ProtobufFieldExtensions)
            }
        });
    },
    extensions: {
        protobufMessage: {
            fullName: "testapis.primitives.Primitives",
            name: "Primitives",
            package: "testapis.primitives"
        }
    }
}), {
    toProto: (input: NexusGen["inputTypes"]["PrimitivesInput"]): $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Primitives => {
        const output = new $$testapis$node_native$lib$$testapis$primitives$primitives_pb.Primitives();
        output.setRequiredDoubleValue(input.requiredDoubleValue);
        output.setRequiredFloatValue(input.requiredFloatValue);
        output.setRequiredInt32Value(input.requiredInt32Value);
        output.setRequiredInt64Value(proto_nexus.stringToNumber(input.requiredInt64Value));
        output.setRequiredUint32Value(input.requiredUint32Value);
        output.setRequiredUint64Value(proto_nexus.stringToNumber(input.requiredUint64Value));
        output.setRequiredSint32Value(input.requiredSint32Value);
        output.setRequiredSint64Value(proto_nexus.stringToNumber(input.requiredSint64Value));
        output.setRequiredFixed32Value(input.requiredFixed32Value);
        output.setRequiredFixed64Value(proto_nexus.stringToNumber(input.requiredFixed64Value));
        output.setRequiredSfixed32Value(input.requiredSfixed32Value);
        output.setRequiredSfixed64Value(proto_nexus.stringToNumber(input.requiredSfixed64Value));
        output.setRequiredBoolValue(input.requiredBoolValue);
        output.setRequiredStringValue(input.requiredStringValue);
        output.setRequiredDoubleValuesList(input.requiredDoubleValues.map(v => v));
        output.setRequiredFloatValuesList(input.requiredFloatValues.map(v => v));
        output.setRequiredInt32ValuesList(input.requiredInt32Values.map(v => v));
        output.setRequiredInt64ValuesList(input.requiredInt64Values.map(v => proto_nexus.stringToNumber(v)));
        output.setRequiredUint32ValuesList(input.requiredUint32Values.map(v => v));
        output.setRequiredUint64ValuesList(input.requiredUint64Values.map(v => proto_nexus.stringToNumber(v)));
        output.setRequiredSint32ValuesList(input.requiredSint32Values.map(v => v));
        output.setRequiredSint64ValuesList(input.requiredSint64Values.map(v => proto_nexus.stringToNumber(v)));
        output.setRequiredFixed32ValuesList(input.requiredFixed32Values.map(v => v));
        output.setRequiredFixed64ValuesList(input.requiredFixed64Values.map(v => proto_nexus.stringToNumber(v)));
        output.setRequiredSfixed32ValuesList(input.requiredSfixed32Values.map(v => v));
        output.setRequiredSfixed64ValuesList(input.requiredSfixed64Values.map(v => proto_nexus.stringToNumber(v)));
        output.setRequiredBoolValuesList(input.requiredBoolValues.map(v => v));
        output.setRequiredStringValuesList(input.requiredStringValues.map(v => v));
        return output;
    },
    _protoNexus: {
        fields: {
            requiredDoubleValue: {
                type: nexus.nonNull("Float"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_double_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredFloatValue: {
                type: nexus.nonNull("Float"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_float_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredInt32Value: {
                type: nexus.nonNull("Int"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_int32_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredInt64Value: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_int64_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredUint32Value: {
                type: nexus.nonNull("Int"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_uint32_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredUint64Value: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_uint64_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSint32Value: {
                type: nexus.nonNull("Int"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sint32_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSint64Value: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sint64_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredFixed32Value: {
                type: nexus.nonNull("Int"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_fixed32_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredFixed64Value: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_fixed64_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSfixed32Value: {
                type: nexus.nonNull("Int"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sfixed32_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSfixed64Value: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sfixed64_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredBoolValue: {
                type: nexus.nonNull("Boolean"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_bool_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredStringValue: {
                type: nexus.nonNull("String"),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_string_value"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredDoubleValues: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Float"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_double_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredFloatValues: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Float"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_float_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredInt32Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_int32_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredInt64Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_int64_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredUint32Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_uint32_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredUint64Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_uint64_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSint32Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sint32_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSint64Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sint64_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredFixed32Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_fixed32_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredFixed64Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_fixed64_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSfixed32Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Int"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sfixed32_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredSfixed64Values: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_sfixed64_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredBoolValues: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("Boolean"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_bool_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            },
            requiredStringValues: {
                type: nexus.nonNull(nexus.list(nexus.nonNull("String"))),
                extensions: {
                    ...({
                        protobufField: {
                            name: "required_string_values"
                        }
                    } as proto_nexus.ProtobufFieldExtensions)
                }
            }
        }
    }
});
