// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-ts-proto/lib/,pothos_builder_path=../builder,scalar=int64=String,scalar=uint64=String,scalar=sint64=String,scalar=fixed64=String,scalar=sfixed64=String,scalar=google.protobuf.Int64Value=String,scalar=google.protobuf.UInt64Value=String,scalar=google.protobuf.SInt64Value=String,scalar=google.protobuf.Fixed64Value=String,scalar=google.protobuf.SFixed64Value=String"
// @generated from file testapis/deprecation/file_deprecation.proto (package testapis.deprecation, syntax proto3)
/* eslint-disable */

import { builder } from "../../../builder";
import {
  DeprecatedFileEnum,
  DeprecatedFileMessage,
  DeprecatedFileMessage_InnerMessage,
} from "@proto-graphql/e2e-testapis-ts-proto/lib/testapis/deprecation/file_deprecation";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const DeprecatedFileMessage$Ref = builder.objectRef<
  DeprecatedFileMessage
>("DeprecatedFileMessage");
builder.objectType(DeprecatedFileMessage$Ref, {
  name: "DeprecatedFileMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
    enum: t.field({
      type: DeprecatedFileEnum$Ref,
      nullable: true,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      resolve: (source) => {
        if (
          source.enum === DeprecatedFileEnum.DEPRECATED_FILE_ENUM_UNSPECIFIED
        ) {
          return null;
        }

        return source.enum;
      },
      extensions: {
        protobufField: {
          name: "enum",
          typeFullName: "testapis.deprecation.DeprecatedFileEnum",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return (source as DeprecatedFileMessage | { $type: string & {}; }).$type ===
      "testapis.deprecation.DeprecatedFileMessage";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage",
      name: "DeprecatedFileMessage",
      package: "testapis.deprecation",
    },
  },
});

export const DeprecatedFileMessageInnerMessage$Ref = builder.objectRef<
  DeprecatedFileMessage_InnerMessage
>("DeprecatedFileMessageInnerMessage");
builder.objectType(DeprecatedFileMessageInnerMessage$Ref, {
  name: "DeprecatedFileMessageInnerMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return (source as DeprecatedFileMessage_InnerMessage | {
      $type: string & {};
    }).$type === "testapis.deprecation.DeprecatedFileMessage.InnerMessage";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage.InnerMessage",
      name: "InnerMessage",
      package: "testapis.deprecation",
    },
  },
});

export type DeprecatedFileMessageInput$Shape = {
  body?: DeprecatedFileMessage["body"] | null;
  enum?: DeprecatedFileMessage["enum"] | null;
};

export const DeprecatedFileMessageInput$Ref: InputObjectRef<
  DeprecatedFileMessageInput$Shape
> = builder.inputRef<DeprecatedFileMessageInput$Shape>(
  "DeprecatedFileMessageInput",
).implement({
  fields: (t) => ({
    body: t.field({
      type: "String",
      required: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
    enum: t.field({
      type: DeprecatedFileEnum$Ref,
      required: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: {
        protobufField: {
          name: "enum",
          typeFullName: "testapis.deprecation.DeprecatedFileEnum",
        },
      },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage",
      name: "DeprecatedFileMessage",
      package: "testapis.deprecation",
    },
  },
});

export type DeprecatedFileMessageInnerMessageInput$Shape = {
  body?: DeprecatedFileMessage_InnerMessage["body"] | null;
};

export const DeprecatedFileMessageInnerMessageInput$Ref: InputObjectRef<
  DeprecatedFileMessageInnerMessageInput$Shape
> = builder.inputRef<DeprecatedFileMessageInnerMessageInput$Shape>(
  "DeprecatedFileMessageInnerMessageInput",
).implement({
  fields: (t) => ({
    body: t.field({
      type: "String",
      required: false,
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.deprecation.DeprecatedFileMessage.InnerMessage",
      name: "InnerMessage",
      package: "testapis.deprecation",
    },
  },
});

export const DeprecatedFileEnum$Ref: EnumRef<
  DeprecatedFileEnum,
  DeprecatedFileEnum
> = builder.enumType("DeprecatedFileEnum", {
  values: {
    DEPRECATED_FILE_FOO: {
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      value: 1,
      extensions: { protobufEnumValue: { name: "DEPRECATED_FILE_FOO" } },
    },
    DEPRECATED_FILE_BAR: {
      deprecationReason:
        "testapis/deprecation/file_deprecation.proto is mark as deprecated.",
      value: 2,
      extensions: { protobufEnumValue: { name: "DEPRECATED_FILE_BAR" } },
    },
  } as const,
  extensions: {
    protobufEnum: {
      name: "DeprecatedFileEnum",
      fullName: "testapis.deprecation.DeprecatedFileEnum",
      package: "testapis.deprecation",
    },
  },
});
