// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es-v1,ignore_non_message_oneof_fields"
// @generated from file testapis/oneof/non_message/non_message.proto (package testapis.oneof.non_message, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import {
  MessageMember,
  OneofParent,
  Status,
} from "@proto-graphql/e2e-testapis-protobuf-es/lib/testapis/oneof/non_message/non_message_pb";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const OneofParent$Ref = builder.objectRef<OneofParent>("OneofParent");
builder.objectType(OneofParent$Ref, {
  name: "OneofParent",
  fields: (t) => ({
    mixedOneofMembers: t.field({
      type: OneofParentMixedOneofMembers$Ref,
      nullable: true,
      resolve: (source) => {
        return (source.mixedOneofMembers.value ?? null) as
          | MessageMember
          | undefined
          | null;
      },
      extensions: { protobufField: { name: "mixed_oneof_members" } },
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof OneofParent;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.oneof.non_message.OneofParent",
      name: "OneofParent",
      package: "testapis.oneof.non_message",
    },
  },
});

export const MessageMember$Ref = builder.objectRef<MessageMember>(
  "MessageMember",
);
builder.objectType(MessageMember$Ref, {
  name: "MessageMember",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof MessageMember;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.oneof.non_message.MessageMember",
      name: "MessageMember",
      package: "testapis.oneof.non_message",
    },
  },
});

export type OneofParentInput$Shape = {
  member?: MessageMemberInput$Shape | null;
};

export const OneofParentInput$Ref: InputObjectRef<OneofParentInput$Shape> =
  builder.inputRef<OneofParentInput$Shape>("OneofParentInput").implement({
    fields: (t) => ({
      member: t.field({
        type: MessageMemberInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "member",
            typeFullName: "testapis.oneof.non_message.MessageMember",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.oneof.non_message.OneofParent",
        name: "OneofParent",
        package: "testapis.oneof.non_message",
      },
    },
  });

export function OneofParentInput$toProto(
  input: OneofParentInput$Shape | null | undefined,
): OneofParent {
  return new OneofParent({
    mixedOneofMembers: input?.member
      ? { case: "member", value: MessageMemberInput$toProto(input.member) }
      : undefined,
  });
}

export type MessageMemberInput$Shape = { body: MessageMember["body"]; };

export const MessageMemberInput$Ref: InputObjectRef<MessageMemberInput$Shape> =
  builder.inputRef<MessageMemberInput$Shape>("MessageMemberInput").implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.oneof.non_message.MessageMember",
        name: "MessageMember",
        package: "testapis.oneof.non_message",
      },
    },
  });

export function MessageMemberInput$toProto(
  input: MessageMemberInput$Shape | null | undefined,
): MessageMember {
  return new MessageMember({ body: input?.body ?? undefined });
}

export const OneofParentMixedOneofMembers$Ref = builder.unionType(
  "OneofParentMixedOneofMembers",
  {
    types: [MessageMember$Ref],
    extensions: {
      protobufOneof: {
        fullName: "testapis.oneof.non_message.OneofParent.mixed_oneof_members",
        name: "mixed_oneof_members",
        messageName: "OneofParent",
        package: "testapis.oneof.non_message",
        fields: [{
          name: "member",
          type: "testapis.oneof.non_message.MessageMember",
        }],
      },
    },
  },
);

export const Status$Ref: EnumRef<Status, Status> = builder.enumType("Status", {
  values: {
    OPEN: {
      value: 1,
      extensions: { protobufEnumValue: { name: "STATUS_OPEN" } },
    },
  } as const,
  extensions: {
    protobufEnum: {
      name: "Status",
      fullName: "testapis.oneof.non_message.Status",
      package: "testapis.oneof.non_message",
    },
  },
});
