#!/usr/bin/env bash

set -eu
set -o pipefail

cd $(dirname $0)/..

PLUGIN_ROOT=./packages/protoc-gen-nexus

./scripts/protocw \
  -I "$PLUGIN_ROOT/include" \
  --plugin=protoc-gen-ts=`yarn bin protoc-gen-ts` \
  --js_out="$PLUGIN_ROOT/src/__generated__/extensions" --js_opt=import_style=commonjs,binary \
  --ts_out="$PLUGIN_ROOT/src/__generated__/extensions" \
  $PLUGIN_ROOT/include/graphql/*.proto
