#!/usr/bin/env bash


set -eu
set -o pipefail

ROOT_DIR=$(dirname $0)/..

PROTOC_VERSION='21.4'
PROTOC_DIR=$ROOT_DIR/tmp/protoc-${PROTOC_VERSION}
PROTOC_BIN=$PROTOC_DIR/bin/protoc

PROTOBUF_JS_VERSION='3.21.2'
PROTOBUF_JS_DIR=$ROOT_DIR/tmp/protobuf-javascript-${PROTOBUF_JS_VERSION}
PROTOBUF_JS_BIN=$PROTOBUF_JS_DIR/bin/protoc-gen-js

unameOs() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    cygwin_nt*) os="windows" ;;
    mingw*) os="windows" ;;
    msys_nt*) os="windows" ;;
    darwin) os="osx" ;;
  esac
  echo "$os"
}

unameArch() {
  if [ "$(unameOs)" = "osx" ]; then
    echo "x86_64"
  else
    uname -m
  fi
}

downloadProtoc() {
  if [ -f $PROTOC_BIN ]; then
    return
  fi

  mkdir -p $PROTOC_DIR

  archive="protoc-${PROTOC_VERSION}-$(unameOs)-$(unameArch).zip"
  curl -sfOL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${archive}
  unzip $archive -d $PROTOC_DIR
  rm -rf $archive
}

downloadProtobufJs() {
  if [ -f $PROTOBUF_JS_BIN ]; then
    return
  fi

  mkdir -p $PROTOBUF_JS_DIR

  archive="protobuf-javascript-${PROTOBUF_JS_VERSION}-$(unameOs)-$(unameArch).zip"
  curl -sfOL https://github.com/protocolbuffers/protobuf-javascript/releases/download/v${PROTOBUF_JS_VERSION}/${archive}
  unzip $archive -d $PROTOBUF_JS_DIR
  rm -rf $archive
}

_main() {
  downloadProtoc
  downloadProtobufJs

  PATH=$PROTOBUF_JS_DIR/bin:$PATH $PROTOC_BIN -I $PROTOC_DIR/include "$@"
}

_main "$@"
