// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es-v2/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es"
// @generated from file testapis/basic/nested/nested.proto (package testapis.basic.nested, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { create, isMessage, MessageShape } from "@bufbuild/protobuf";
import {
  ParentMessage,
  ParentMessage_NestedEnum,
  ParentMessage_NestedMessage,
  ParentMessage_NestedMessageSchema,
  ParentMessageSchema,
} from "@proto-graphql/e2e-testapis-protobuf-es-v2/lib/testapis/basic/nested/nested_pb";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const ParentMessage$Ref = builder.objectRef<
  MessageShape<typeof ParentMessageSchema>
>("ParentMessage");
builder.objectType(ParentMessage$Ref, {
  name: "ParentMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
    nested: t.expose("nested", {
      type: ParentMessageNestedMessage$Ref,
      nullable: true,
      extensions: {
        protobufField: {
          name: "nested",
          typeFullName: "testapis.basic.nested.ParentMessage.NestedMessage",
        },
      },
    }),
    nestedEnum: t.field({
      type: ParentMessageNestedEnum$Ref,
      nullable: true,
      resolve: (source) => {
        if (
          source.nestedEnum === ParentMessage_NestedEnum.NESTED_ENUM_UNSPECIFIED
        ) {
          return null;
        }

        return source.nestedEnum;
      },
      extensions: {
        protobufField: {
          name: "nested_enum",
          typeFullName: "testapis.basic.nested.ParentMessage.NestedEnum",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, ParentMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.basic.nested.ParentMessage",
      name: "ParentMessage",
      package: "testapis.basic.nested",
    },
  },
});

export const ParentMessageNestedMessage$Ref = builder.objectRef<
  MessageShape<typeof ParentMessage_NestedMessageSchema>
>("ParentMessageNestedMessage");
builder.objectType(ParentMessageNestedMessage$Ref, {
  name: "ParentMessageNestedMessage",
  fields: (t) => ({
    nestedBody: t.expose("nestedBody", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "nested_body", typeFullName: "string" },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, ParentMessage_NestedMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.basic.nested.ParentMessage.NestedMessage",
      name: "NestedMessage",
      package: "testapis.basic.nested",
    },
  },
});

export type ParentMessageInput$Shape = {
  body: ParentMessage["body"];
  nested?: ParentMessageNestedMessageInput$Shape | null;
  nestedEnum?: ParentMessage["nestedEnum"] | null;
};

export const ParentMessageInput$Ref: InputObjectRef<ParentMessageInput$Shape> =
  builder.inputRef<ParentMessageInput$Shape>("ParentMessageInput").implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
      nested: t.field({
        type: ParentMessageNestedMessageInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "nested",
            typeFullName: "testapis.basic.nested.ParentMessage.NestedMessage",
          },
        },
      }),
      nestedEnum: t.field({
        type: ParentMessageNestedEnum$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "nested_enum",
            typeFullName: "testapis.basic.nested.ParentMessage.NestedEnum",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.basic.nested.ParentMessage",
        name: "ParentMessage",
        package: "testapis.basic.nested",
      },
    },
  }) as InputObjectRef<ParentMessageInput$Shape>;

export function ParentMessageInput$toProto(
  input: ParentMessageInput$Shape | null | undefined,
): ParentMessage {
  return create(ParentMessageSchema, {
    body: input?.body ?? undefined,
    nested: input?.nested
      ? ParentMessageNestedMessageInput$toProto(input.nested)
      : undefined,
    nestedEnum: input?.nestedEnum ?? undefined,
  });
}

export type ParentMessageNestedMessageInput$Shape = {
  nestedBody: ParentMessage_NestedMessage["nestedBody"];
};

export const ParentMessageNestedMessageInput$Ref: InputObjectRef<
  ParentMessageNestedMessageInput$Shape
> = builder.inputRef<ParentMessageNestedMessageInput$Shape>(
  "ParentMessageNestedMessageInput",
).implement({
  fields: (t) => ({
    nestedBody: t.field({
      type: "String",
      required: true,
      extensions: {
        protobufField: { name: "nested_body", typeFullName: "string" },
      },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.basic.nested.ParentMessage.NestedMessage",
      name: "NestedMessage",
      package: "testapis.basic.nested",
    },
  },
}) as InputObjectRef<ParentMessageNestedMessageInput$Shape>;

export function ParentMessageNestedMessageInput$toProto(
  input: ParentMessageNestedMessageInput$Shape | null | undefined,
): ParentMessage_NestedMessage {
  return create(ParentMessage_NestedMessageSchema, {
    nestedBody: input?.nestedBody ?? undefined,
  });
}

export const ParentMessageNestedEnum$Ref: EnumRef<
  ParentMessage_NestedEnum,
  ParentMessage_NestedEnum
> = builder.enumType("ParentMessageNestedEnum", {
  values: {
    FOO: { value: 1, extensions: { protobufEnumValue: { name: "FOO" } } },
    BAR: { value: 2, extensions: { protobufEnumValue: { name: "BAR" } } },
  } as const,
  extensions: {
    protobufEnum: {
      name: "NestedEnum",
      fullName: "testapis.basic.nested.ParentMessage.NestedEnum",
      package: "testapis.basic.nested",
    },
  },
});
