// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es-v1"
// @generated from file testapis/edgecases/import_squashed_union/pkg1/types.proto (package testapis.edgecases.import_squashed_union.pkg1, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../../builder";
import {
  OneofMessage1,
  SquashedOneof,
} from "@proto-graphql/e2e-testapis-protobuf-es/lib/testapis/edgecases/import_squashed_union/pkg1/types_pb";
import { InputObjectRef } from "@pothos/core";

export const OneofMessage1$Ref = builder.objectRef<OneofMessage1>(
  "OneofMessage1",
);
builder.objectType(OneofMessage1$Ref, {
  name: "OneofMessage1",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return source instanceof OneofMessage1;
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.edgecases.import_squashed_union.pkg1.OneofMessage1",
      name: "OneofMessage1",
      package: "testapis.edgecases.import_squashed_union.pkg1",
    },
  },
});

export type OneofMessage1Input$Shape = { body: OneofMessage1["body"]; };

export const OneofMessage1Input$Ref: InputObjectRef<OneofMessage1Input$Shape> =
  builder.inputRef<OneofMessage1Input$Shape>("OneofMessage1Input").implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.edgecases.import_squashed_union.pkg1.OneofMessage1",
        name: "OneofMessage1",
        package: "testapis.edgecases.import_squashed_union.pkg1",
      },
    },
  });

export function OneofMessage1Input$toProto(
  input: OneofMessage1Input$Shape | null | undefined,
): OneofMessage1 {
  return new OneofMessage1({ body: input?.body ?? undefined });
}

export type SquashedOneofInput$Shape = {
  msg1?: OneofMessage1Input$Shape | null;
};

export const SquashedOneofInput$Ref: InputObjectRef<SquashedOneofInput$Shape> =
  builder.inputRef<SquashedOneofInput$Shape>("SquashedOneofInput").implement({
    fields: (t) => ({
      msg1: t.field({
        type: OneofMessage1Input$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "msg1",
            typeFullName:
              "testapis.edgecases.import_squashed_union.pkg1.OneofMessage1",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.edgecases.import_squashed_union.pkg1.SquashedOneof",
        name: "SquashedOneof",
        package: "testapis.edgecases.import_squashed_union.pkg1",
        options: { "[graphql.object_type]": { squashUnion: true } },
      },
    },
  });

export function SquashedOneofInput$toProto(
  input: SquashedOneofInput$Shape | null | undefined,
): SquashedOneof {
  return new SquashedOneof({
    message: input?.msg1
      ? { case: "msg1", value: OneofMessage1Input$toProto(input.msg1) }
      : undefined,
  });
}

export const SquashedOneof$Ref = builder.unionType("SquashedOneof", {
  types: [OneofMessage1$Ref],
  extensions: {
    protobufOneof: {
      fullName: "testapis.edgecases.import_squashed_union.pkg1.SquashedOneof",
      name: "SquashedOneof",
      package: "testapis.edgecases.import_squashed_union.pkg1",
      fields: [{
        name: "msg1",
        type: "testapis.edgecases.import_squashed_union.pkg1.OneofMessage1",
        options: { "[graphql.object_type]": { squashUnion: true } },
      }],
    },
  },
});
