// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-ts-proto/lib/,pothos_builder_path=../builder,scalar=int64=String,scalar=uint64=String,scalar=sint64=String,scalar=fixed64=String,scalar=sfixed64=String,scalar=google.protobuf.Int64Value=String,scalar=google.protobuf.UInt64Value=String,scalar=google.protobuf.SInt64Value=String,scalar=google.protobuf.Fixed64Value=String,scalar=google.protobuf.SFixed64Value=String"
// @generated from file testapis/multipkgs/subpkg1/types.proto (package testapis.multipkgs.subpkg1, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import {
  SubpkgEnum,
  SubpkgMessage,
} from "@proto-graphql/e2e-testapis-ts-proto/lib/testapis/multipkgs/subpkg1/types";
import { EnumRef, InputObjectRef } from "@pothos/core";

export const SubpkgMessage$Ref = builder.objectRef<SubpkgMessage>(
  "SubpkgMessage",
);
builder.objectType(SubpkgMessage$Ref, {
  name: "SubpkgMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return (source as SubpkgMessage | { $type: string & {}; }).$type ===
      "testapis.multipkgs.subpkg1.SubpkgMessage";
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
      name: "SubpkgMessage",
      package: "testapis.multipkgs.subpkg1",
    },
  },
});

export type SubpkgMessageInput$Shape = { body: SubpkgMessage["body"]; };

export const SubpkgMessageInput$Ref: InputObjectRef<SubpkgMessageInput$Shape> =
  builder.inputRef<SubpkgMessageInput$Shape>("SubpkgMessageInput").implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.multipkgs.subpkg1.SubpkgMessage",
        name: "SubpkgMessage",
        package: "testapis.multipkgs.subpkg1",
      },
    },
  });

export const SubpkgEnum$Ref: EnumRef<SubpkgEnum, SubpkgEnum> = builder.enumType(
  "SubpkgEnum",
  {
    values: {
      FOO: { value: 1, extensions: { protobufEnumValue: { name: "FOO" } } },
      BAR: { value: 2, extensions: { protobufEnumValue: { name: "BAR" } } },
    } as const,
    extensions: {
      protobufEnum: {
        name: "SubpkgEnum",
        fullName: "testapis.multipkgs.subpkg1.SubpkgEnum",
        package: "testapis.multipkgs.subpkg1",
      },
    },
  },
);
