// Code generated by protoc-gen-nexus. DO NOT EDIT.
// source: testapis/enums/enums.proto

import { objectType, inputObjectType, enumType, nullable, nonNull } from "nexus";
import * as $$testapis$node_native$lib$testapis$enums$enums_pb from "@testapis/node-native/lib/testapis/enums/enums_pb";
export type $$testapis$node_native$lib$testapis$enums$enums_pb$MessageWithEnums = $$testapis$node_native$lib$testapis$enums$enums_pb.MessageWithEnums;
export const MessageWithEnums = objectType({
    name: "MessageWithEnums",
    description: "",
    definition(t) {
        t.field("requiredMyEnum", {
            type: nonNull("MyEnum"),
            description: "Required.",
            resolve(root) {
                if (root.getRequiredMyEnum == null) {
                    throw new Error("MessageWithEnums.requiredMyEnum is required field. But got null or unspecified.");
                }
                if (root.getRequiredMyEnum === $$testapis$node_native$lib$testapis$enums$enums_pb.MyEnum.MY_ENUM_UNSPECIFIED) {
                    throw new Error("MessageWithEnums.requiredMyEnum is required field. But got null or unspecified.");
                }
                return root.getRequiredMyEnum;
            }
        });
        t.field("optionalMyEnum", {
            type: nullable("MyEnum"),
            description: "Optional.",
            resolve(root) {
                if (root.getOptionalMyEnum == null) {
                    return null;
                }
                if (root.getOptionalMyEnum === $$testapis$node_native$lib$testapis$enums$enums_pb.MyEnum.MY_ENUM_UNSPECIFIED) {
                    return null;
                }
                return root.getOptionalMyEnum;
            }
        });
        t.field("requiredMyEnumWithoutUnspecified", {
            type: nonNull("MyEnumWithoutUnspecified"),
            description: "Required.",
            resolve(root) {
                if (root.getRequiredMyEnumWithoutUnspecified == null) {
                    throw new Error("MessageWithEnums.requiredMyEnumWithoutUnspecified is required field. But got null or unspecified.");
                }
                return root.getRequiredMyEnumWithoutUnspecified;
            }
        });
        t.field("optionalMyEnumWithoutUnspecified", {
            type: nullable("MyEnumWithoutUnspecified"),
            description: "Optional.",
            resolve(root) {
                if (root.getOptionalMyEnumWithoutUnspecified == null) {
                    return null;
                }
                return root.getOptionalMyEnumWithoutUnspecified;
            }
        });
    },
    sourceType: { module: __filename, export: "$$testapis$node_native$lib$testapis$enums$enums_pb$MessageWithEnums" }
});
export const MessageWithEnumsInput = inputObjectType({
    name: "MessageWithEnumsInput",
    description: "",
    definition(t) {
        t.field("requiredMyEnum", {
            type: nonNull("MyEnum"),
            description: "Required."
        });
        t.field("optionalMyEnum", {
            type: nullable("MyEnum"),
            description: "Optional."
        });
        t.field("requiredMyEnumWithoutUnspecified", {
            type: nonNull("MyEnumWithoutUnspecified"),
            description: "Required."
        });
        t.field("optionalMyEnumWithoutUnspecified", {
            type: nullable("MyEnumWithoutUnspecified"),
            description: "Optional."
        });
    }
});
export const MyEnum = enumType({
    name: "MyEnum",
    description: "",
    members: [
        {
            name: "MY_ENUM_FOO",
            value: 1
        },
        {
            name: "MY_ENUM_BAR",
            description: "This is Bar.",
            value: 2
        },
        {
            name: "MY_ENUM_BAZ",
            value: 3
        }
    ]
});
export const MyEnumWithoutUnspecified = enumType({
    name: "MyEnumWithoutUnspecified",
    description: "",
    members: [
        {
            name: "MY_ENUM_WITHOUT_UNSPECIFIED_FOO",
            value: 0
        },
        {
            name: "MY_ENUM_WITHOUT_UNSPECIFIED_BAR",
            value: 1
        },
        {
            name: "MY_ENUM_WITHOUT_UNSPECIFIED_BAZ",
            value: 2
        }
    ]
});
