// @generated by protoc-gen-pothos v0.6.2 with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es-v2/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es"
// @generated from file testapis/edgecases/import_from_same_pkg/child.proto (package testapis.edgecases.import_from_same_pkg, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { create, isMessage, MessageShape } from "@bufbuild/protobuf";
import {
  ChildMessage,
  ChildMessageSchema,
} from "@proto-graphql/e2e-testapis-protobuf-es-v2/lib/testapis/edgecases/import_from_same_pkg/child_pb";
import { InputObjectRef } from "@pothos/core";

export const ChildMessage$Ref = builder.objectRef<
  MessageShape<typeof ChildMessageSchema>
>("ChildMessage");
builder.objectType(ChildMessage$Ref, {
  name: "ChildMessage",
  fields: (t) => ({
    body: t.expose("body", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "body", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, ChildMessageSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.edgecases.import_from_same_pkg.ChildMessage",
      name: "ChildMessage",
      package: "testapis.edgecases.import_from_same_pkg",
    },
  },
});

export type ChildMessageInput$Shape = { body: ChildMessage["body"]; };

export const ChildMessageInput$Ref: InputObjectRef<ChildMessageInput$Shape> =
  builder.inputRef<ChildMessageInput$Shape>("ChildMessageInput").implement({
    fields: (t) => ({
      body: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "body", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.edgecases.import_from_same_pkg.ChildMessage",
        name: "ChildMessage",
        package: "testapis.edgecases.import_from_same_pkg",
      },
    },
  }) as InputObjectRef<ChildMessageInput$Shape>;

export function ChildMessageInput$toProto(
  input: ChildMessageInput$Shape | null | undefined,
): ChildMessage {
  return create(ChildMessageSchema, { body: input?.body ?? undefined });
}
