// @generated by protoc-gen-pothos vX.Y.Z with parameter "import_prefix=@proto-graphql/e2e-testapis-protobuf-es-v2/lib/,pothos_builder_path=../builder,protobuf_lib=protobuf-es"
// @generated from file testapis/service/basic/basic.proto (package testapis.service.basic, syntax proto3)
/* eslint-disable */

import { builder } from "../../../../builder";
import { create, isMessage, MessageShape } from "@bufbuild/protobuf";
import {
  Address,
  AddressSchema,
  CreateUserRequest,
  CreateUserRequestSchema,
  EmailContact,
  EmailContactSchema,
  GetUserRequest,
  GetUserRequestSchema,
  InternalSyncRequest,
  InternalSyncRequestSchema,
  PhoneContact,
  PhoneContactSchema,
  Profile,
  ProfileSchema,
  RenameUserRequest,
  RenameUserRequestSchema,
  Role,
  SearchUsersRequest,
  SearchUsersRequestSchema,
  SearchUsersResponse,
  SearchUsersResponseSchema,
  User,
  UserSchema,
  UserService,
  WorkAddress,
  WorkAddressSchema,
} from "@proto-graphql/e2e-testapis-protobuf-es-v2/lib/testapis/service/basic/basic_pb";
import { EnumRef, InputObjectRef } from "@pothos/core";
import { getClient } from "@proto-graphql/connect-runtime";
import { callRpc } from "@proto-graphql/connect-runtime/graphql";

export const User$Ref = builder.objectRef<MessageShape<typeof UserSchema>>(
  "User",
);
builder.objectType(User$Ref, {
  name: "User",
  fields: (t) => ({
    id: t.expose("id", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: {
          name: "id",
          typeFullName: "string",
          options: { "[graphql.field]": { id: true } },
        },
      },
    }),
    name: t.expose("name", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "name", typeFullName: "string" } },
    }),
    bio: t.expose("bio", {
      type: "String",
      nullable: true,
      extensions: { protobufField: { name: "bio", typeFullName: "string" } },
    }),
    role: t.field({
      type: Role$Ref,
      nullable: true,
      resolve: (source) => {
        if (source.role === Role.UNSPECIFIED) {
          return null;
        }

        return source.role;
      },
      extensions: {
        protobufField: {
          name: "role",
          typeFullName: "testapis.service.basic.Role",
        },
      },
    }),
    address: t.expose("address", {
      type: Address$Ref,
      nullable: true,
      extensions: {
        protobufField: {
          name: "address",
          typeFullName: "testapis.service.basic.Address",
        },
      },
    }),
    profile: t.expose("profile", {
      type: Profile$Ref,
      nullable: true,
      extensions: {
        protobufField: {
          name: "profile",
          typeFullName: "testapis.service.basic.Profile",
        },
      },
    }),
    contact: t.field({
      type: UserContact$Ref,
      nullable: true,
      resolve: (source) => {
        return (source.contact.value ?? null) as
          | EmailContact
          | PhoneContact
          | undefined
          | null;
      },
      extensions: { protobufField: { name: "contact" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, UserSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.User",
      name: "User",
      package: "testapis.service.basic",
    },
  },
});

export const Profile$Ref = builder.objectRef<
  MessageShape<typeof ProfileSchema>
>("Profile");
builder.objectType(Profile$Ref, {
  name: "Profile",
  fields: (t) => ({
    headline: t.expose("headline", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "headline", typeFullName: "string" },
      },
    }),
    avatarUrl: t.expose("avatarUrl", {
      type: "String",
      nullable: true,
      extensions: {
        protobufField: { name: "avatar_url", typeFullName: "string" },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, ProfileSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.Profile",
      name: "Profile",
      package: "testapis.service.basic",
    },
  },
});

export const EmailContact$Ref = builder.objectRef<
  MessageShape<typeof EmailContactSchema>
>("EmailContact");
builder.objectType(EmailContact$Ref, {
  name: "EmailContact",
  fields: (t) => ({
    email: t.expose("email", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "email", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, EmailContactSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.EmailContact",
      name: "EmailContact",
      package: "testapis.service.basic",
    },
  },
});

export const PhoneContact$Ref = builder.objectRef<
  MessageShape<typeof PhoneContactSchema>
>("PhoneContact");
builder.objectType(PhoneContact$Ref, {
  name: "PhoneContact",
  fields: (t) => ({
    phoneNumber: t.expose("phoneNumber", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "phone_number", typeFullName: "string" },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, PhoneContactSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.PhoneContact",
      name: "PhoneContact",
      package: "testapis.service.basic",
    },
  },
});

export const Address$Ref = builder.objectRef<
  MessageShape<typeof AddressSchema>
>("Address");
builder.objectType(Address$Ref, {
  name: "Address",
  fields: (t) => ({
    city: t.expose("city", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "city", typeFullName: "string" } },
    }),
    zip: t.expose("zip", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "zip", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, AddressSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.Address",
      name: "Address",
      package: "testapis.service.basic",
    },
  },
});

export const GetUserRequest$Ref = builder.objectRef<
  MessageShape<typeof GetUserRequestSchema>
>("GetUserRequest");
builder.objectType(GetUserRequest$Ref, {
  name: "GetUserRequest",
  fields: (t) => ({
    userId: t.expose("userId", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "user_id", typeFullName: "string" },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, GetUserRequestSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.GetUserRequest",
      name: "GetUserRequest",
      package: "testapis.service.basic",
    },
  },
});

export const SearchUsersRequest$Ref = builder.objectRef<
  MessageShape<typeof SearchUsersRequestSchema>
>("SearchUsersRequest");
builder.objectType(SearchUsersRequest$Ref, {
  name: "SearchUsersRequest",
  fields: (t) => ({
    queryText: t.expose("queryText", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "query_text", typeFullName: "string" },
      },
    }),
    limit: t.expose("limit", {
      type: "Int",
      nullable: true,
      extensions: { protobufField: { name: "limit", typeFullName: "int32" } },
    }),
    role: t.field({
      type: Role$Ref,
      nullable: true,
      resolve: (source) => {
        if (source.role === Role.UNSPECIFIED) {
          return null;
        }

        return source.role;
      },
      extensions: {
        protobufField: {
          name: "role",
          typeFullName: "testapis.service.basic.Role",
        },
      },
    }),
    address: t.expose("address", {
      type: Address$Ref,
      nullable: true,
      extensions: {
        protobufField: {
          name: "address",
          typeFullName: "testapis.service.basic.Address",
        },
      },
    }),
    filter: t.field({
      type: SearchUsersRequestFilter$Ref,
      nullable: true,
      description:
        "`work` uses a distinct message type from `home` (GraphQL union member\n types must be unique).",
      resolve: (source) => {
        return (source.filter.value ?? null) as
          | Address
          | WorkAddress
          | undefined
          | null;
      },
      extensions: { protobufField: { name: "filter" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, SearchUsersRequestSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.SearchUsersRequest",
      name: "SearchUsersRequest",
      package: "testapis.service.basic",
    },
  },
});

export const WorkAddress$Ref = builder.objectRef<
  MessageShape<typeof WorkAddressSchema>
>("WorkAddress");
builder.objectType(WorkAddress$Ref, {
  name: "WorkAddress",
  fields: (t) => ({
    city: t.expose("city", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "city", typeFullName: "string" } },
    }),
    zip: t.expose("zip", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "zip", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, WorkAddressSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.WorkAddress",
      name: "WorkAddress",
      package: "testapis.service.basic",
    },
  },
});

export const SearchUsersResponse$Ref = builder.objectRef<
  MessageShape<typeof SearchUsersResponseSchema>
>("SearchUsersResponse");
builder.objectType(SearchUsersResponse$Ref, {
  name: "SearchUsersResponse",
  fields: (t) => ({
    users: t.expose("users", {
      type: [User$Ref],
      nullable: { list: true, items: false },
      extensions: {
        protobufField: {
          name: "users",
          typeFullName: "testapis.service.basic.User",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, SearchUsersResponseSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.SearchUsersResponse",
      name: "SearchUsersResponse",
      package: "testapis.service.basic",
    },
  },
});

export const CreateUserRequest$Ref = builder.objectRef<
  MessageShape<typeof CreateUserRequestSchema>
>("CreateUserRequest");
builder.objectType(CreateUserRequest$Ref, {
  name: "CreateUserRequest",
  fields: (t) => ({
    name: t.expose("name", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "name", typeFullName: "string" } },
    }),
    address: t.expose("address", {
      type: Address$Ref,
      nullable: true,
      extensions: {
        protobufField: {
          name: "address",
          typeFullName: "testapis.service.basic.Address",
        },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, CreateUserRequestSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.CreateUserRequest",
      name: "CreateUserRequest",
      package: "testapis.service.basic",
    },
  },
});

export const RenameUserRequest$Ref = builder.objectRef<
  MessageShape<typeof RenameUserRequestSchema>
>("RenameUserRequest");
builder.objectType(RenameUserRequest$Ref, {
  name: "RenameUserRequest",
  fields: (t) => ({
    userId: t.expose("userId", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "user_id", typeFullName: "string" },
      },
    }),
    newName: t.expose("newName", {
      type: "String",
      nullable: false,
      extensions: {
        protobufField: { name: "new_name", typeFullName: "string" },
      },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, RenameUserRequestSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.RenameUserRequest",
      name: "RenameUserRequest",
      package: "testapis.service.basic",
    },
  },
});

export const InternalSyncRequest$Ref = builder.objectRef<
  MessageShape<typeof InternalSyncRequestSchema>
>("InternalSyncRequest");
builder.objectType(InternalSyncRequest$Ref, {
  name: "InternalSyncRequest",
  fields: (t) => ({
    cursor: t.expose("cursor", {
      type: "String",
      nullable: false,
      extensions: { protobufField: { name: "cursor", typeFullName: "string" } },
    }),
  }),
  isTypeOf: (source) => {
    return isMessage(source, InternalSyncRequestSchema);
  },
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.InternalSyncRequest",
      name: "InternalSyncRequest",
      package: "testapis.service.basic",
    },
  },
});

export type UserInput$Shape = {
  id: User["id"];
  name: User["name"];
  bio?: User["bio"] | null;
  role?: User["role"] | null;
  address?: AddressInput$Shape | null;
  profile?: ProfileInput$Shape | null;
  emailContact?: EmailContactInput$Shape | null;
  phoneContact?: PhoneContactInput$Shape | null;
};

export const UserInput$Ref: InputObjectRef<UserInput$Shape> = builder.inputRef<
  UserInput$Shape
>("UserInput").implement({
  fields: (t) => ({
    id: t.field({
      type: "String",
      required: true,
      extensions: {
        protobufField: {
          name: "id",
          typeFullName: "string",
          options: { "[graphql.field]": { id: true } },
        },
      },
    }),
    name: t.field({
      type: "String",
      required: true,
      extensions: { protobufField: { name: "name", typeFullName: "string" } },
    }),
    bio: t.field({
      type: "String",
      required: false,
      extensions: { protobufField: { name: "bio", typeFullName: "string" } },
    }),
    role: t.field({
      type: Role$Ref,
      required: false,
      extensions: {
        protobufField: {
          name: "role",
          typeFullName: "testapis.service.basic.Role",
        },
      },
    }),
    address: t.field({
      type: AddressInput$Ref,
      required: false,
      extensions: {
        protobufField: {
          name: "address",
          typeFullName: "testapis.service.basic.Address",
        },
      },
    }),
    profile: t.field({
      type: ProfileInput$Ref,
      required: false,
      extensions: {
        protobufField: {
          name: "profile",
          typeFullName: "testapis.service.basic.Profile",
        },
      },
    }),
    emailContact: t.field({
      type: EmailContactInput$Ref,
      required: false,
      extensions: {
        protobufField: {
          name: "email_contact",
          typeFullName: "testapis.service.basic.EmailContact",
        },
      },
    }),
    phoneContact: t.field({
      type: PhoneContactInput$Ref,
      required: false,
      extensions: {
        protobufField: {
          name: "phone_contact",
          typeFullName: "testapis.service.basic.PhoneContact",
        },
      },
    }),
  }),
  extensions: {
    protobufMessage: {
      fullName: "testapis.service.basic.User",
      name: "User",
      package: "testapis.service.basic",
    },
  },
}) as InputObjectRef<UserInput$Shape>;

export function UserInput$toProto(
  input: UserInput$Shape | null | undefined,
): User {
  return create(UserSchema, {
    id: input?.id ?? undefined,
    name: input?.name ?? undefined,
    bio: input?.bio ?? undefined,
    role: input?.role ?? undefined,
    address: input?.address ? AddressInput$toProto(input.address) : undefined,
    profile: input?.profile ? ProfileInput$toProto(input.profile) : undefined,
    contact: input?.emailContact
      ? {
        case: "emailContact",
        value: EmailContactInput$toProto(input.emailContact),
      }
      : input?.phoneContact
      ? {
        case: "phoneContact",
        value: PhoneContactInput$toProto(input.phoneContact),
      }
      : undefined,
  });
}

export type ProfileInput$Shape = {
  headline: Profile["headline"];
  avatarUrl?: Profile["avatarUrl"] | null;
};

export const ProfileInput$Ref: InputObjectRef<ProfileInput$Shape> = builder
  .inputRef<ProfileInput$Shape>("ProfileInput").implement({
    fields: (t) => ({
      headline: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "headline", typeFullName: "string" },
        },
      }),
      avatarUrl: t.field({
        type: "String",
        required: false,
        extensions: {
          protobufField: { name: "avatar_url", typeFullName: "string" },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.Profile",
        name: "Profile",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<ProfileInput$Shape>;

export function ProfileInput$toProto(
  input: ProfileInput$Shape | null | undefined,
): Profile {
  return create(ProfileSchema, {
    headline: input?.headline ?? undefined,
    avatarUrl: input?.avatarUrl ?? undefined,
  });
}

export type EmailContactInput$Shape = { email: EmailContact["email"]; };

export const EmailContactInput$Ref: InputObjectRef<EmailContactInput$Shape> =
  builder.inputRef<EmailContactInput$Shape>("EmailContactInput").implement({
    fields: (t) => ({
      email: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "email", typeFullName: "string" },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.EmailContact",
        name: "EmailContact",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<EmailContactInput$Shape>;

export function EmailContactInput$toProto(
  input: EmailContactInput$Shape | null | undefined,
): EmailContact {
  return create(EmailContactSchema, { email: input?.email ?? undefined });
}

export type PhoneContactInput$Shape = {
  phoneNumber: PhoneContact["phoneNumber"];
};

export const PhoneContactInput$Ref: InputObjectRef<PhoneContactInput$Shape> =
  builder.inputRef<PhoneContactInput$Shape>("PhoneContactInput").implement({
    fields: (t) => ({
      phoneNumber: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "phone_number", typeFullName: "string" },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.PhoneContact",
        name: "PhoneContact",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<PhoneContactInput$Shape>;

export function PhoneContactInput$toProto(
  input: PhoneContactInput$Shape | null | undefined,
): PhoneContact {
  return create(PhoneContactSchema, {
    phoneNumber: input?.phoneNumber ?? undefined,
  });
}

export type AddressInput$Shape = {
  city: Address["city"];
  zip: Address["zip"];
};

export const AddressInput$Ref: InputObjectRef<AddressInput$Shape> = builder
  .inputRef<AddressInput$Shape>("AddressInput").implement({
    fields: (t) => ({
      city: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "city", typeFullName: "string" } },
      }),
      zip: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "zip", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.Address",
        name: "Address",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<AddressInput$Shape>;

export function AddressInput$toProto(
  input: AddressInput$Shape | null | undefined,
): Address {
  return create(AddressSchema, {
    city: input?.city ?? undefined,
    zip: input?.zip ?? undefined,
  });
}

export type GetUserRequestInput$Shape = { userId: GetUserRequest["userId"]; };

export const GetUserRequestInput$Ref: InputObjectRef<
  GetUserRequestInput$Shape
> = builder.inputRef<GetUserRequestInput$Shape>("GetUserRequestInput")
  .implement({
    fields: (t) => ({
      userId: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "user_id", typeFullName: "string" },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.GetUserRequest",
        name: "GetUserRequest",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<GetUserRequestInput$Shape>;

export function GetUserRequestInput$toProto(
  input: GetUserRequestInput$Shape | null | undefined,
): GetUserRequest {
  return create(GetUserRequestSchema, { userId: input?.userId ?? undefined });
}

export type SearchUsersRequestInput$Shape = {
  queryText: SearchUsersRequest["queryText"];
  limit?: SearchUsersRequest["limit"] | null;
  role?: SearchUsersRequest["role"] | null;
  address?: AddressInput$Shape | null;
  home?: AddressInput$Shape | null;
  work?: WorkAddressInput$Shape | null;
};

export const SearchUsersRequestInput$Ref: InputObjectRef<
  SearchUsersRequestInput$Shape
> = builder.inputRef<SearchUsersRequestInput$Shape>("SearchUsersRequestInput")
  .implement({
    fields: (t) => ({
      queryText: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "query_text", typeFullName: "string" },
        },
      }),
      limit: t.field({
        type: "Int",
        required: false,
        extensions: { protobufField: { name: "limit", typeFullName: "int32" } },
      }),
      role: t.field({
        type: Role$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "role",
            typeFullName: "testapis.service.basic.Role",
          },
        },
      }),
      address: t.field({
        type: AddressInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "address",
            typeFullName: "testapis.service.basic.Address",
          },
        },
      }),
      home: t.field({
        type: AddressInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "home",
            typeFullName: "testapis.service.basic.Address",
          },
        },
      }),
      work: t.field({
        type: WorkAddressInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "work",
            typeFullName: "testapis.service.basic.WorkAddress",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.SearchUsersRequest",
        name: "SearchUsersRequest",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<SearchUsersRequestInput$Shape>;

export function SearchUsersRequestInput$toProto(
  input: SearchUsersRequestInput$Shape | null | undefined,
): SearchUsersRequest {
  return create(SearchUsersRequestSchema, {
    queryText: input?.queryText ?? undefined,
    limit: input?.limit ?? undefined,
    role: input?.role ?? undefined,
    address: input?.address ? AddressInput$toProto(input.address) : undefined,
    filter: input?.home
      ? { case: "home", value: AddressInput$toProto(input.home) }
      : input?.work
      ? { case: "work", value: WorkAddressInput$toProto(input.work) }
      : undefined,
  });
}

export type WorkAddressInput$Shape = {
  city: WorkAddress["city"];
  zip: WorkAddress["zip"];
};

export const WorkAddressInput$Ref: InputObjectRef<WorkAddressInput$Shape> =
  builder.inputRef<WorkAddressInput$Shape>("WorkAddressInput").implement({
    fields: (t) => ({
      city: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "city", typeFullName: "string" } },
      }),
      zip: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "zip", typeFullName: "string" } },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.WorkAddress",
        name: "WorkAddress",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<WorkAddressInput$Shape>;

export function WorkAddressInput$toProto(
  input: WorkAddressInput$Shape | null | undefined,
): WorkAddress {
  return create(WorkAddressSchema, {
    city: input?.city ?? undefined,
    zip: input?.zip ?? undefined,
  });
}

export type SearchUsersResponseInput$Shape = {
  users?: Array<UserInput$Shape> | null;
};

export const SearchUsersResponseInput$Ref: InputObjectRef<
  SearchUsersResponseInput$Shape
> = builder.inputRef<SearchUsersResponseInput$Shape>("SearchUsersResponseInput")
  .implement({
    fields: (t) => ({
      users: t.field({
        type: [UserInput$Ref],
        required: { list: false, items: true },
        extensions: {
          protobufField: {
            name: "users",
            typeFullName: "testapis.service.basic.User",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.SearchUsersResponse",
        name: "SearchUsersResponse",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<SearchUsersResponseInput$Shape>;

export function SearchUsersResponseInput$toProto(
  input: SearchUsersResponseInput$Shape | null | undefined,
): SearchUsersResponse {
  return create(SearchUsersResponseSchema, {
    users: input?.users?.map((v) => UserInput$toProto(v)),
  });
}

export type CreateUserRequestInput$Shape = {
  name: CreateUserRequest["name"];
  address?: AddressInput$Shape | null;
};

export const CreateUserRequestInput$Ref: InputObjectRef<
  CreateUserRequestInput$Shape
> = builder.inputRef<CreateUserRequestInput$Shape>("CreateUserRequestInput")
  .implement({
    fields: (t) => ({
      name: t.field({
        type: "String",
        required: true,
        extensions: { protobufField: { name: "name", typeFullName: "string" } },
      }),
      address: t.field({
        type: AddressInput$Ref,
        required: false,
        extensions: {
          protobufField: {
            name: "address",
            typeFullName: "testapis.service.basic.Address",
          },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.CreateUserRequest",
        name: "CreateUserRequest",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<CreateUserRequestInput$Shape>;

export function CreateUserRequestInput$toProto(
  input: CreateUserRequestInput$Shape | null | undefined,
): CreateUserRequest {
  return create(CreateUserRequestSchema, {
    name: input?.name ?? undefined,
    address: input?.address ? AddressInput$toProto(input.address) : undefined,
  });
}

export type RenameUserRequestInput$Shape = {
  userId: RenameUserRequest["userId"];
  newName: RenameUserRequest["newName"];
};

export const RenameUserRequestInput$Ref: InputObjectRef<
  RenameUserRequestInput$Shape
> = builder.inputRef<RenameUserRequestInput$Shape>("RenameUserRequestInput")
  .implement({
    fields: (t) => ({
      userId: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "user_id", typeFullName: "string" },
        },
      }),
      newName: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "new_name", typeFullName: "string" },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.RenameUserRequest",
        name: "RenameUserRequest",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<RenameUserRequestInput$Shape>;

export function RenameUserRequestInput$toProto(
  input: RenameUserRequestInput$Shape | null | undefined,
): RenameUserRequest {
  return create(RenameUserRequestSchema, {
    userId: input?.userId ?? undefined,
    newName: input?.newName ?? undefined,
  });
}

export type InternalSyncRequestInput$Shape = {
  cursor: InternalSyncRequest["cursor"];
};

export const InternalSyncRequestInput$Ref: InputObjectRef<
  InternalSyncRequestInput$Shape
> = builder.inputRef<InternalSyncRequestInput$Shape>("InternalSyncRequestInput")
  .implement({
    fields: (t) => ({
      cursor: t.field({
        type: "String",
        required: true,
        extensions: {
          protobufField: { name: "cursor", typeFullName: "string" },
        },
      }),
    }),
    extensions: {
      protobufMessage: {
        fullName: "testapis.service.basic.InternalSyncRequest",
        name: "InternalSyncRequest",
        package: "testapis.service.basic",
      },
    },
  }) as InputObjectRef<InternalSyncRequestInput$Shape>;

export function InternalSyncRequestInput$toProto(
  input: InternalSyncRequestInput$Shape | null | undefined,
): InternalSyncRequest {
  return create(InternalSyncRequestSchema, {
    cursor: input?.cursor ?? undefined,
  });
}

export const UserContact$Ref = builder.unionType("UserContact", {
  types: [EmailContact$Ref, PhoneContact$Ref],
  extensions: {
    protobufOneof: {
      fullName: "testapis.service.basic.User.contact",
      name: "contact",
      messageName: "User",
      package: "testapis.service.basic",
      fields: [{
        name: "email_contact",
        type: "testapis.service.basic.EmailContact",
      }, {
        name: "phone_contact",
        type: "testapis.service.basic.PhoneContact",
      }],
    },
  },
});

export const SearchUsersRequestFilter$Ref = builder.unionType(
  "SearchUsersRequestFilter",
  {
    types: [Address$Ref, WorkAddress$Ref],
    description:
      "`work` uses a distinct message type from `home` (GraphQL union member\n types must be unique).",
    extensions: {
      protobufOneof: {
        fullName: "testapis.service.basic.SearchUsersRequest.filter",
        name: "filter",
        messageName: "SearchUsersRequest",
        package: "testapis.service.basic",
        fields: [{ name: "home", type: "testapis.service.basic.Address" }, {
          name: "work",
          type: "testapis.service.basic.WorkAddress",
        }],
      },
    },
  },
);

export const Role$Ref: EnumRef<Role, Role> = builder.enumType("Role", {
  values: {
    ADMIN: {
      value: 1,
      extensions: { protobufEnumValue: { name: "ROLE_ADMIN" } },
    },
    USER: {
      value: 2,
      extensions: { protobufEnumValue: { name: "ROLE_USER" } },
    },
  } as const,
  extensions: {
    protobufEnum: {
      name: "Role",
      fullName: "testapis.service.basic.Role",
      package: "testapis.service.basic",
    },
  },
});

builder.queryField(
  "getUser",
  (t) =>
    t.field({
      type: User$Ref,
      nullable: false,
      args: { userId: t.arg({ type: "String", required: true }) },
      resolve: async (_root, args, ctx) => {
        const client = getClient(ctx, UserService);
        const res = await callRpc(ctx, (opts) =>
          client.getUser(
            create(GetUserRequestSchema, { userId: args.userId ?? undefined }),
            opts,
          ));
        return res;
      },
      extensions: {
        protobufMethod: {
          name: "GetUser",
          fullName: "testapis.service.basic.UserService.GetUser",
          service: "testapis.service.basic.UserService",
          package: "testapis.service.basic",
        },
      },
    }),
);

builder.queryField(
  "searchUsers",
  (t) =>
    t.field({
      type: [User$Ref],
      nullable: { list: true, items: false },
      args: {
        queryText: t.arg({ type: "String", required: true }),
        limit: t.arg({ type: "Int", required: false }),
        role: t.arg({ type: Role$Ref, required: false }),
        address: t.arg({ type: AddressInput$Ref, required: false }),
        home: t.arg({ type: AddressInput$Ref, required: false }),
        work: t.arg({ type: WorkAddressInput$Ref, required: false }),
      },
      resolve: async (_root, args, ctx) => {
        const client = getClient(ctx, UserService);
        const res = await callRpc(ctx, (opts) =>
          client.searchUsers(
            create(SearchUsersRequestSchema, {
              queryText: args.queryText ?? undefined,
              limit: args.limit ?? undefined,
              role: args.role ?? undefined,
              address: args.address
                ? AddressInput$toProto(args.address)
                : undefined,
              filter: args.home
                ? { case: "home", value: AddressInput$toProto(args.home) }
                : args.work
                ? { case: "work", value: WorkAddressInput$toProto(args.work) }
                : undefined,
            }),
            opts,
          ));
        return res.users;
      },
      extensions: {
        protobufMethod: {
          name: "SearchUsers",
          fullName: "testapis.service.basic.UserService.SearchUsers",
          service: "testapis.service.basic.UserService",
          package: "testapis.service.basic",
        },
      },
    }),
);

builder.mutationField(
  "createUser",
  (t) =>
    t.field({
      type: User$Ref,
      nullable: false,
      args: {
        input: t.arg({ type: CreateUserRequestInput$Ref, required: true }),
      },
      resolve: async (_root, args, ctx) => {
        const client = getClient(ctx, UserService);
        const res = await callRpc(
          ctx,
          (opts) =>
            client.createUser(CreateUserRequestInput$toProto(args.input), opts),
        );
        return res;
      },
      extensions: {
        protobufMethod: {
          name: "CreateUser",
          fullName: "testapis.service.basic.UserService.CreateUser",
          service: "testapis.service.basic.UserService",
          package: "testapis.service.basic",
        },
      },
    }),
);

builder.mutationField(
  "updateUserName",
  (t) =>
    t.field({
      type: User$Ref,
      nullable: false,
      args: {
        input: t.arg({ type: RenameUserRequestInput$Ref, required: true }),
      },
      resolve: async (_root, args, ctx) => {
        const client = getClient(ctx, UserService);
        const res = await callRpc(
          ctx,
          (opts) =>
            client.renameUser(RenameUserRequestInput$toProto(args.input), opts),
        );
        return res;
      },
      extensions: {
        protobufMethod: {
          name: "RenameUser",
          fullName: "testapis.service.basic.UserService.RenameUser",
          service: "testapis.service.basic.UserService",
          package: "testapis.service.basic",
        },
      },
    }),
);

builder.queryField(
  "pingUser",
  (t) =>
    t.field({
      type: "Boolean",
      nullable: false,
      args: { userId: t.arg({ type: "String", required: true }) },
      resolve: async (_root, args, ctx) => {
        const client = getClient(ctx, UserService);
        await callRpc(ctx, (opts) =>
          client.pingUser(
            create(GetUserRequestSchema, { userId: args.userId ?? undefined }),
            opts,
          ));
        return true;
      },
      extensions: {
        protobufMethod: {
          name: "PingUser",
          fullName: "testapis.service.basic.UserService.PingUser",
          service: "testapis.service.basic.UserService",
          package: "testapis.service.basic",
        },
      },
    }),
);

builder.mutationField(
  "deleteUser",
  (t) =>
    t.field({
      type: "Boolean",
      nullable: false,
      args: { input: t.arg({ type: GetUserRequestInput$Ref, required: true }) },
      resolve: async (_root, args, ctx) => {
        const client = getClient(ctx, UserService);
        await callRpc(
          ctx,
          (opts) =>
            client.deleteUser(GetUserRequestInput$toProto(args.input), opts),
        );
        return true;
      },
      extensions: {
        protobufMethod: {
          name: "DeleteUser",
          fullName: "testapis.service.basic.UserService.DeleteUser",
          service: "testapis.service.basic.UserService",
          package: "testapis.service.basic",
        },
      },
    }),
);
